### DISCUSSION TITLE
Instagram icon with colors

### DISCUSSION THREAD

**Discussion by kamalsprasad** [vuetifyjs/vuetify#12381] [Q&A] [answered]
Hi, how do I modify <v-icon>mdi-instagram</v-icon> with the color gradient?

TIA

**Comment by Renato66** [comment, marked as answer]
Following the [brandgradients](http://www.brandgradients.com/instagram-colors/)

```vue
<v-icon class="instagram-gradient">mdi-instagram</v-icon>
```
```css
.instagram-gradient {
  background: -webkit-linear-gradient(45deg, #405de6, #5851db, #833ab4, #c13584, #e1306c, #fd1d1d);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
```
![image](https://user-images.githubusercontent.com/9284273/96515159-35ce1200-123b-11eb-9ebc-5ca25306163e.png)
