### DISCUSSION TITLE
Scrollbar Color Support (Theme-colored scrollbars)

### DISCUSSION THREAD

**Discussion by gouthamkrishnakv** [vuetifyjs/vuetify#13902] [Ideas]
Support for the `scrollbar-color` [CSS Property](https://drafts.csswg.org/css-scrollbars/#scrollbar-color) which would let the browser color the scrollbar as per the application requirements.

Mozilla Firefox (since ver. `64`) has supported this and the following browsers are implementing it presently in their present, next release or one of the future releases:
- *Mozilla Firefox*: Since version `64` (Partially Implemented, `light` and `dark` aren't working, but color scrollbars do).
- *Chromium/Google Chrome*: To be implemented (tracked feature status [here](https://www.chromestatus.com/feature/5665308343795712), partial support with prefix `-webkit-`).
- *Apple Safari*: `15 Technical Preview` (To be implemented, partial support with prefix `-webkit-`).
- *Microsoft Edge*: (same as Chrome/Chromium).

It's essentially 2 colors added using the `scrollbar-color` CSS Property (It's a kinda-trial, I'm not as well versed in how CSS works here, so forgive me for that):
```scss
html, body {
  scrollbar-color: $primary $secondary;
  /* first color is the thumb/scroller part,
     and the second is the scrollbar background
     part.
  */
}
```

MDN Documentation about `scrollbar-color` [here](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color).
CanIUse about `scrollbar-color` [here](https://caniuse.com/css-scrollbar).
CSSWG Draft on `scrollbar-color` [here](https://drafts.csswg.org/css-scrollbars/).
