### DISCUSSION TITLE
[Feature Request] How i can use my own SASS file globally?

### DISCUSSION THREAD

**Discussion by approached** [vuetifyjs/vuetify#14727] [Q&A] [answered]
### Problem to solve
I can't use my own sass file. I can only to override css class or set variables. But no posible to use a own `main.sass` file. 

Loading file: `lib/presets/default/index.js`
Doc: https://vuetifyjs.com/en/customization/presets ... `import '../../styles/main.sass'`

### Proposed solution
Load sass template via option.

**Comment by ottz0** [comment]
I used @import in my App.vue file with style tags and it compiles and reloads

**Comment by approached** [comment]
@ottz0 how it will work? can you please send a example.After you load vuetify intitally than the main.sass will also load. You have no choice!

**Comment by ottz0** [comment]
Put it in your App.vue file and import it

```
<style lang="scss">
    @import 'src/scss/main';
</style>
```

**Comment by approached** [comment]
What you are describe, it's extend the main file and not a full placement!
BTW: I use a https://vuetifyjs.com/en/getting-started/quick-start#webpack-install .

**Comment by KaelWD** [comment]
Please explain what you're actually trying to do.

**Comment by approached** [comment]
The File `import '../../styles/main.sass'` generates follow css code:

```css
.v-application code {
    background-color: #f5f5f5;
    color: #bd4147;
    box-shadow: 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12);
}
```

But i want use my own css style for the code tag and not overwrite this!
