### DISCUSSION TITLE
v-progress-linear animation speed

### DISCUSSION THREAD

**Discussion by the-supercoach** [vuetifyjs/vuetify#16012] [Q&A] [answered]
Hi guys, the v-progress-linear animation is a lovely feature, however I doubt I'm alone in feeling it's a little too fast for my liking.
I noted that there's a SASS variable listed on the API page ([progress-linear-indeteminate-animation-duration](https://next.vuetifyjs.com/en/api/v-progress-linear/#props-progress-linear-indeteminate-animation-duration)) which suggests that there's a way to slow it down, but I can't for the life of me figure out how to actually modify the speed.
I'm not familiar with SASS and spent a couple of hours going down a rabbit hole trying to work out how to use it to help my cause, all to no avail. Surely there's got to be an easy way to modify the speed of this thing right?

**Comment by KaelWD** [comment, marked as answer]
Sass documentation is here: https://next.vuetifyjs.com/en/features/sass-variables/#component-specific-variables

You can always just override the CSS though:
```css
.v-progress-linear__indeterminate .long,
.v-progress-linear__indeterminate .short {
  animation-duration: 3s;
}
```
