### DISCUSSION TITLE
How to align height of an element with an VTextField input in v3?

### DISCUSSION THREAD

**Discussion by binaryfunt** [vuetifyjs/vuetify#16584] [Q&A]
I'm trying to make the height of the element containing the equals sign the same as the height of the `v-text-field`'s input. As you can see below it is not aligned at the moment because the `v-text-field` has an extra area below the input that increases its height.

![image](https://user-images.githubusercontent.com/14579418/216651507-413fdeb8-1671-4c20-baf3-a2849750b7fc.png)

In Vuetify v2 this was possible by using the `$text-field-filled-full-width-outlined-single-line-slot-min-height` SASS variable, but this is gone in v3. I have inspected the CSS and found that the height of the input comes from
```css
.v-input--density-compact {
  --v-input-control-height: 40px;
}
```

I've tried
```scss
.equals {
  @extend .v-input--density-compact;
  height: var(--v-input-control-height);
}
```
However this results in `SassError: The target selector was not found.`
