### ISSUE TITLE
[Feature Request] Overwriting Heading variables

### ISSUE THREAD

**Issue by ottz0** [vuetifyjs/vuetify#10546]
### Problem to solve
I am trying to overwrite the Vuetify Heading variables. I am using the variables.scss file in the scss folder as per setup and this works correctly as I can update $border-radius-root and $card-elevation variables in which it updates.

Iv'e looked at the vuetify SASS docs and have put the following in my variables doc

$headings: (
  'h1': (
    'size': 8.3125rem,
    'line-height': 1.15em
  )
)

However it doe not update.

What are the steps and process to update and overwrite the $headings variables for H1,H2,body-1 etc as I have tried every approach.

### Proposed solution
Documentation on how to update and overwrite heading variables

**Comment by Tarabass** [comment]
Are you also defining the style onto a h1 like this?

```css
h1 {
  font-size: map-deep-get($headings, 'h1', 'size');
  line-height: map-deep-get($headings, 'h1', 'line-height');
}
```
