### ISSUE TITLE
[Bug Report] Form components wrongly disable input events on child components

### ISSUE THREAD

**Issue by tvld** [vuetifyjs/vuetify#10708]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0
**OS:** Ubuntu undefined

### Steps to reproduce
- disable an input component such as in v-treeview or v-checkbox
```js
<template v-slot:label="{ item }">
    <span>{{ item.title() }}</span>
    <v-icon @click.prevent="showHelp(item)">mdi-information-outline</v-icon>
</template>
```

### Expected Behavior
- in disabled input components,  @click events should still be possible  on child components,
- now they do not

### Actual Behavior
No pointer is shown, clicking does not work

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/NWqjZxP" target="_blank">https://codepen.io/jkarczm/pen/NWqjZxP</a>

### Other comments
For example: I like to show an info bubble when a user clicks on a (i) icon in any label, so also the disabled, of the tree node.

**Comment by jacekkarczmarczyk** [comment]
Workaround https://codepen.io/jkarczm/pen/abOwbOL?editors=1100

**Comment by tvld** [comment]
Excellent, thanks, for ``v-treeview`` this works for me:
```scss
.v-treeview-node--click.v-treeview-node--disabled {
  pointer-events: initial;
}
.v-treeview-node--click.v-treeview-node--disabled .v-treeview-node__checkbox {
  pointer-events: none;
}
.v-treeview-node--click.v-treeview-node--disabled .v-treeview-node__label {
  cursor: default;
}
```
