### ISSUE TITLE
Toolbar height is adjusted based on max-width and orientation, main .container is not.

### ISSUE THREAD

**Issue by rlightner** [vuetifyjs/vuetify#1075]
```css
.toolbar__content {
    height: 64px;
}
@media (max-width: 1424px) and (orientation: landscape)
.toolbar__content, .toolbar__extension {
    height: 48px;
}
```
this does not take the width / height change into account:
```css
.application--toolbar.application--footer>main>.container {
    min-height: calc(100vh - 64px - 36px);
}
```
This causes:
![image](https://user-images.githubusercontent.com/354640/28432180-db19e688-6d3b-11e7-83c1-cae900de734c.png)
to jump up:
![image](https://user-images.githubusercontent.com/354640/28432178-d589a1a4-6d3b-11e7-8f12-862a3306b7f6.png)
