### ISSUE TITLE
[Bug Report] v-slider IE11 misalignment of ticks/labels

### ISSUE THREAD

**Issue by jamesdruhan** [vuetifyjs/vuetify#11111]
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
```javascript
<v-card color="accent">
    <v-img class="white--text align-end" height="150px" src="../../assets/image/reports_year_1.png" >
        <v-card-title class="font-weight-bold">Reports</v-card-title>
    </v-img>

    <v-card-text class="pb-0">
    <v-slider v-model="reportYear" :tick-labels="reportYears" step="1" ticks="always" tick-size="4" :max="3" color="white" dark></v-slider>
    </v-card-text>
</v-card>
```

![Example Image](https://i.imgur.com/IHHd2Ni.png)

Any <v-slider> that uses ticks and labels will reproduce the issue. **Unable to use Codepen/JSFiddle because they don't support IE**.

This can be solved by adding a top:15px; to the container of the slider (only for IE):

```css
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none)
{  
    .v-slider__ticks-container
    {
        position : absolute;
        top      : 15px !important;
    }
}
```

### Expected Behavior
Ticks should align with the slider bar and labels should be below.

### Actual Behavior
Ticks appear above slider bar and labels appear inside slider bar.

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>
