### ISSUE TITLE
[Feature Request] Allow to set opacity value of v-tooltip

### ISSUE THREAD

**Issue by Bastczuak** [vuetifyjs/vuetify#11184]
### Problem to solve
Right now the opacity of tooltips is set hard to 90% by inline styles when active https://github.com/vuetifyjs/vuetify/blob/b120d01e04587c0e00e8762e94c43268ed2cfe63/packages/vuetify/src/components/VTooltip/VTooltip.ts#L135. But I want to change the opacity so I can have tooltips with 100% opacity for example.

### Proposed solution
Add another property called `opacity` to `v-tooltip` to be able to change the inline style opacity value.

**Comment by Hyperion2400** [comment]
Please add this in the next version.

**Comment by genygilles** [comment]
As a workaround, you can use this in a global (S)CSS file:

```css
.v-tooltip__content.menuable__content__active {
  opacity: 1!important;
}

```

**Comment by iyush1993** [comment]
The easiest way I found was to specify the opacity in a class and assign that class to `content-class` prop of tooltip

```scss
.custom-tooltip {
    opacity: 1!important;
}
```

then in v-tooltip, assign this class:
```vue
<v-tooltip content-class='custom-tooltip'>
</v-tooltip>
```

**Comment by webcoderkz** [comment]
@iyush1993 

in my case background color needed to be modified:

```
.custom-tooltip {
  opacity: 1 !important;
  background: rgba(97, 97, 97, 1);
}
```

**Comment by codeflorist** [comment]
this is a current global solution without needing a custom class:

```css
.v-tooltip .v-overlay__content {
    background: rgba(var(--v-theme-surface-variant), 1) !important;
}
```

**Comment by NickSomsen** [comment]
For me using `:deep()` selector worked (Vuetify `3.1.7`):

```css
:deep(.v-overlay__content) {
  background: rgba(66, 66, 66, 1) !important; /* 66, 66, 66 = --v-theme-surface-variant; 1 for opacity */
}
```

Use a custom class to target only specific tooltips:

```html
<v-tooltip class='custom-tooltip'>
</v-tooltip>
```
```css
.custom-opacity :deep(.v-overlay__content) {
  background: rgba(66, 66, 66, 1) !important;
}
```
