### ISSUE TITLE
[Feature Request] improve nested grid gutters

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#11408]
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Mac OS 10.15.3

### Steps to reproduce
Nest a grid inside another.

### Expected Behavior
The gutters to remain the same between all columns of all grids.

### Actual Behavior
Gutters around columns of the nested grid are larger.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/qBOMdpY" target="_blank">https://codepen.io/thomaskientz/pen/qBOMdpY</a>

**Comment by uodami** [comment]
Hi,
Is there any news about this bug?

Thanks,
Imad

**Comment by ThomasKientz** [comment]
@KaelWD @jacekkarczmarczyk ping

**Comment by Jaffsterz** [comment]
This has totally wrecked the layout of loads of our pages :(

**Comment by KaelWD** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com/) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by halimb** [comment]
this is a breaking change, in a non major release, especially with such a central component as `v-row`,  production applications layouts will be broken...

I'm asking, what's the quick workaround for this, instead of going through all the v-rows in my app to restore the original vertical spacing?

**Comment by Jaffsterz** [comment]
Yes it's a nightmare - we have a very large number of pages and they were all wrecked by this change.

Nobody responded to my raising it in my post above though so we have had to spend many hours going through all the pages and fixing them.

**Comment by halimb** [comment]
For anyone having a busy Monday debugging this, here's a quick and dirty fix :
```scss
/**
 * Temporary fix for breaking change in Vuetify v-grid
 * (see : https://github.com/vuetifyjs/vuetify/issues/12848)
 * TODO - remove this after migration
 */
.row:not([class*="my-"]):not([class*="ma-"]) {
  margin-top: 0 !important;
  margin-bottom: 0 !important;
}
```
