### ISSUE TITLE
v-select hides too much text of labels before and after selecting an option on small screens

### ISSUE THREAD

**Issue by lobosan** [vuetifyjs/vuetify#1155]
### Steps to reproduce
Open the [codepen](https://codepen.io/lobosan/pen/jLbNeJ/) and shrink the screen up to 372px (this simulates the resolution of my phone)

### Versions
vue 2.4.2, vuetify 0.14.7

### What is expected ?
It should allow to show a bit more text on labels. In my example for instance there is enough room for the whole text since there's only 4 letters left, so the text could go up to about 20px before the down arrow icon. 

Also when an option is selected, the label should re-calculate the space available for the text to appear before adding the ... at the end.

Alternatively, instead of adding the 3 dots, maybe the label could be wrapped in several lines

### What is actually happening ?
The text gets wrapped and 3 dots (...) are added at the end even though there is space to show it completely
![image](https://user-images.githubusercontent.com/314886/28682904-443e1872-72c4-11e7-80f4-54c31070f29b.png)

Also when an option is selected, the label becomes smaller and therefore there is even more room for the label to appear completely, so it should be re calculated instead of only be shrinked.
![image](https://user-images.githubusercontent.com/314886/28683150-1da59b6c-72c5-11e7-8f85-acf26aad8d71.png)

### Reproduction Link
https://codepen.io/lobosan/pen/jLbNeJ/

**Comment by johnleider** [comment]
Label text wrapping is not in spec. Upping ellipsis point from 80% to 90% maximum width.

**Comment by lobosan** [comment]
@johnleider the change in the ellipsis point will only fix the first issue, however the text shown in the label when an option is selected should recalculate the space available since this text is smaller than before and therefore there's more room for the label to appear

**Comment by johnleider** [comment]
I'm not sure I understand what you mean.

**Comment by lobosan** [comment]
@johnleider have a look at my second image above. When I select the option "Artes plásticas y visuales", then the font size of the original label "Ámbito de la actividad principal" becomes smaller and moves a few pixels above the selected option. Since this new style for label is smaller than before and also goes on top of the actual selected option, then it has more space to properly show the text. What should be expected is that even if long label isn't shown completely before selecting an option, after that it could be shown completely

**Comment by johnleider** [comment]
My fix I pushed up should solve this, for the most part. Label's should not wrap, so at a certain length, depending on screen size, it has to ellipsis.

**Comment by lobosan** [comment]
Sure but shouldn't that ellipsis work independently in each case, one for the original label and another for the smaller label after selecting an option?

**Comment by flybayer** [comment]
@lobosan @johnleider I was also having this problem where the label has an unnecessary ellipsis when the label is transformed above the input.

I fixed it with this.
```css
.input-group--text-field.input-group--dirty:not(.input-group--textarea) label,
.input-group--text-field:not(.input-group--single-line).input-group--focused:not(.input-group--textarea) label,
.input-group--text-field:not(.input-group--single-line):focus:not(.input-group--textarea) label {
  min-width: 133%; /* This makes label same width as input when transformed above the input */
}
```
