### ISSUE TITLE
[Bug Report] Hover prop doesn't work (works when outlined)

### ISSUE THREAD

**Issue by yerzhant** [vuetifyjs/vuetify#11672]
### Environment
**Vuetify Version:** 2.3.1
**Last working version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Linux x86_64

### Steps to reproduce
Move mouse over a card

### Expected Behavior
Hover effect

### Actual Behavior
No hover effect

### Reproduction Link
<a href="https://codepen.io/yerzhant/pen/zYroQez?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcards%2F" target="_blank">https://codepen.io/yerzhant/pen/zYroQez?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcards%2F</a>

**Comment by megaroeny** [comment]
This happens with any card I use from the Docs site, using the Codepen example icon button. Doesn't have to be Outlined either.

**Comment by tomparle** [comment]
I confirm the bug. It used to work with version 2.2.x, and seems it appears from v 2.3.0.

**Comment by andrewharvey** [comment]
Until the PR is merged and released, here is a workaround:

```css
.v-card--hover:hover, .v-card--hover:focus {
  box-shadow: 0px 5px 5px -3px rgba(0, 0, 0, 0.2), 0px 8px 10px 1px rgba(0, 0, 0, 0.14), 0px 3px 14px 2px rgba(0, 0, 0, 0.12) !important;
}
```
