### ISSUE TITLE
[Feature Request] grid support for v-virtual-scroll

### ISSUE THREAD

**Issue by aleksey-hoffman** [vuetifyjs/vuetify#11756]
### Problem to solve
Right now `v-virtual-scroll` doesn't support CSS grids, so you cannot use it for image galleries / file managers / etc.

### Proposed solution

Demo of a desired structure (dynamic item height + grid support):
https://codepen.io/aQW5z9fe/pen/GRoMYYp

I didn't have time to figure out a proper way to do it, but here's some pseudo-code:

```html
<v-virtual-scroll>
  <template v-slot="{ item }">   
    <v-virtual-scroll-item
      height="dynamic"
      :grid="grid"
      :class="{
         'small-grid': itemHeight(item) === 64,
         'medium-grid': itemHeight(item) === 180,
      }"
      :min-item-height="32"
      :item-height="itemHeight(item)"
    >
      <custom-header-item
        v-if="item.isHeader"
        :item="item"
      >
        {{item.title}}
      </custom-header-item>

      <custom-item 
        v-if="!item.isHeader"
        :item="item"
      ></custom-item>
    </v-virtual-scroll-item>
  </template>   
</v-virtual-scroll>
```
```js
methods: {
  itemHeight (item) {
    if (item.type === 'header') { return 32 }
    else if (item.type === 'image') { return 180 }
    else { return 64 }
  }
}
```
```css
.medium-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  grid-auto-rows: 180px; 
  grid-gap: 24px;
}

.small-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  grid-auto-rows: 64px;
  grid-gap: 24px;
}
```

**Comment by aleksey-hoffman** [comment]
Never mind, I figured I can achieve this just by passing rows of items:
```html
<v-virtual-scroll
  :items="itemRows"
  item-height="52"
>
  <template v-slot="{ item, index }">
    <item-row
      :key="`item-row-${index}`"
      :row="item" 
      :rowIndex="index"
     ></item-row>
  </template>
</v-virtual-scroll>
```
```js
itemRows () {
  return  lodash.chunk(this.item, 3)
}
```
## ItemRow.vue
```html
<template>
  <div class="grid">
    <div
      v-for="(item, index) in row"
      :key="index"
    >
      <item
        :key="`item-${item.path}`"
        :item="item"
      ></item>
    </div>
  </div>
</template>
```
```css
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  grid-auto-rows: 52px;
  grid-gap: 16px;
}
```
