### ISSUE TITLE
[Feature Request] Add text-pre-wrap

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#11761]
### Problem to solve
We already have a `text-no-wrap` class. If we could use a `text-pre-wrap` we can apply it to `content-class` of `v-tooltip` and use a string containing `\n`.

### Proposed solution
Add a new CSS class `text-pre-wrap`

```scss
.v-application {
  .text-pre-wrap {
    white-space: pre-wrap !important;
  }
}
```

Update documentation https://vuetifyjs.com/en/styles/text-and-typography/#text-wrapping-and-overflow
