### ISSUE TITLE
[Feature Request] Expose all Vuetify theme attributes as SASS/SCSS/CSS variables.

### ISSUE THREAD

**Issue by ajslater** [vuetifyjs/vuetify#11783]
### Problem to solve
Vuetify themes define a variety of CSS attributes, but do not expose them as variables that can be read in the style block.

It looks like a very small subset of variables are exported as CSS variables, which is nice, but not enough to be comprehensive (or helpful to me).

### Proposed solution
export every single attribute in a theme as sass, scss or css variables that can be read in the style block.

There are around 130 attributes defined in the dark theme, for instance:
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/styles/settings/_dark.scss

export them so I can use them in the style block:
```
<style lang="scss">
body {
  background: $vuetify.currentTheme.background;
}
.myCustomCalendarComponent {
  background-color: $vuetify.currentTheme.calendar.backgroundColor;
}
</style>
```
I really only care about the current theme. And the namespace I use as an example above I'm not attached to.

**Comment by wlf100220** [comment]
[feature exists](https://vuetifyjs.com/en/customization/theme/#custom-properties)

**Comment by ajslater** [comment]
I'm pretty sure the feature you mention is the limited set of CSS variables that only expose 10-12 attribute colors.
e.g. https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/services/theme/__tests__/__snapshots__/theme-utils.spec.ts.snap
```
  --v-anchor-base: #c42742;
  --v-primary-base: #c42742;
  --v-primary-lighten5: #2c0447;
  --v-primary-lighten4: #cfa854;
  --v-primary-lighten3: #dd88cc;
  --v-primary-lighten2: #b49921;
  --v-primary-lighten1: #f899c7;
  --v-primary-darken1: #0169dc;
  --v-primary-darken2: #c28fd0;
  --v-primary-darken3: #fbe002;
  --v-primary-darken4: #33303a;
```

While these are CSS variables (and are much better than nothing), the feature request is to expose the 100+ attribute values defined by the themes. While this may be the sum total of all colors used in a theme, there's no way to tell which one is used as the background, or for headers. Only the anchor color is semantically designated.
Also other theme attributes like `inactive-icon-percent': 0.5` are not exported and that could be useful to people trying to make their CSS match a base theme.

**Comment by wlf100220** [comment]
The feature has already expose all theme colors.
The property af for you mentioned, `inactive-icon-percent`, should be defined in scss or sass. Because themes defined in js/ts only contains colors: primary, secondary, accent, success, info, error etc. You can check the type of `VuetifyThemeVariant` and `VuetifyParsedThemeItem`.

### Theme variable compiled in my case:
```css
:root {
    --v-anchor-base: #4caf50;
    --v-primary-base: #4caf50;
    --v-primary-lighten5: #dcffd6;
    --v-primary-lighten4: #beffba;
    --v-primary-lighten3: #a2ff9e;
    --v-primary-lighten2: #85e783;
    --v-primary-lighten1: #69cb69;
    --v-primary-darken1: #2d9437;
    --v-primary-darken2: #00791e;
    --v-primary-darken3: #006000;
    --v-primary-darken4: #004700;
    --v-secondary-base: #03a9f4;
    --v-secondary-lighten5: #d0ffff;
    --v-secondary-lighten4: #b0ffff;
    --v-secondary-lighten3: #90fdff;
    --v-secondary-lighten2: #6ee0ff;
    --v-secondary-lighten1: #48c4ff;
    --v-secondary-darken1: #008fd7;
    --v-secondary-darken2: #0075bb;
    --v-secondary-darken3: #005da0;
    --v-secondary-darken4: #004685;
    --v-accent-base: #9c27b0;
    --v-accent-lighten5: #ffb6ff;
    --v-accent-lighten4: #ff9aff;
    --v-accent-lighten3: #f47eff;
    --v-accent-lighten2: #d662e8;
    --v-accent-lighten1: #b946cc;
    --v-accent-darken1: #800095;
    --v-accent-darken2: #64007b;
    --v-accent-darken3: #490061;
    --v-accent-darken4: #300049;
    --v-error-base: #ff5252;
    --v-error-lighten5: #ffe4d5;
    --v-error-lighten4: #ffc6b9;
    --v-error-lighten3: #ffa99e;
    --v-error-lighten2: #ff8c84;
    --v-error-lighten1: #ff6f6a;
    --v-error-darken1: #df323b;
    --v-error-darken2: #bf0025;
    --v-error-darken3: #9f0010;
    --v-error-darken4: #800000;
    --v-info-base: #00cae3;
    --v-info-lighten5: #cfffff;
    --v-info-lighten4: #b0ffff;
    --v-info-lighten3: #8fffff;
    --v-info-lighten2: #6effff;
    --v-info-lighten1: #48e6ff;
    --v-info-darken1: #00aec7;
    --v-info-darken2: #0093ac;
    --v-info-darken3: #007991;
    --v-info-darken4: #006077;
    --v-success-base: #4caf50;
    --v-success-lighten5: #dcffd6;
    --v-success-lighten4: #beffba;
    --v-success-lighten3: #a2ff9e;
    --v-success-lighten2: #85e783;
    --v-success-lighten1: #69cb69;
    --v-success-darken1: #2d9437;
    --v-success-darken2: #00791e;
    --v-success-darken3: #006000;
    --v-success-darken4: #004700;
    --v-warning-base: #fb8c00;
    --v-warning-lighten5: #ffff9e;
    --v-warning-lighten4: #fffb82;
    --v-warning-lighten3: #ffdf67;
    --v-warning-lighten2: #ffc24b;
    --v-warning-lighten1: #ffa72d;
    --v-warning-darken1: #db7200;
    --v-warning-darken2: #bb5900;
    --v-warning-darken3: #9d4000;
    --v-warning-darken4: #802700;
}
```
