### ISSUE TITLE
[Feature Request] Make individual items in v-treeview selectable

### ISSUE THREAD

**Issue by cjsedwards** [vuetifyjs/vuetify#11813]
### Problem to solve
I have a use case where I don't want every node in the tree to have a checkbox.  I'm getting around this right now by inserting my own custom checkboxes and toggling them.

### Proposed solution
If an item has selectable: false, hide the checkbox even if selectable is true on the v-treeview.

Alternatively, if selectable is true on v-treeview, but I have selectable: true on an individual item, show a checkbox for that item.

**Comment by jakubstankowski** [comment]
it will be a great option and very helpfull...

**Comment by sugoidesune** [comment]
For anyone needing it now i made a CSS solution:

```scss
.v-treeview-node__toggle + button {
 display: none !important;
}
```

**Comment by giovannimanzoni** [comment]
> ```css
> .button.v-treeview-node__toggle + button.v-treeview-node__checkbox {
>  display: none !important;
> }
> ```

the code must be

```css
button.v-treeview-node__toggle + button.v-treeview-node__checkbox {
 display: none !important;
}
```

without the dot on the first selector !
