### ISSUE TITLE
[Feature Request] Better way to customize label color

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#11999]
### Problem to solve
It's currently very hard to alter the color of form input labels. By default it's set using `.theme--light.v-label`.

People have to come up with workarounds, using for example global css and `!important`:  
https://stackoverflow.com/questions/54373084/how-to-change-override-the-default-color-of-a-switch-label-in-vuetify

Looking at the code it seems to use secondary color, but customizing this doesn't seem to have an impact. 
https://github.com/vuetifyjs/vuetify/blob/47325bfb6a71afd9f3d7bb00f65c4785f49ee7a1/packages/vuetify/src/components/VLabel/VLabel.sass#L3-L5

### Proposed solution
I'm not sure what approach would fit Vuetify best, but some ideas:
- Adding a `label` theme property, just like the existing `anchor` property, see [Theme customization](https://vuetifyjs.com/en/customization/theme/#customizing ) for more info.
- Add a SASS/SCSS variable. [More info](https://vuetifyjs.com/en/customization/sass-variables/#variable-api). 
- ...

Ideally this is applied to all form input & control labels.

**Comment by peteruithoven** [comment]
My current workaround:

``` scss
// global.scss
@import "~vuetify/src/styles/styles.sass";

.v-label.theme--light {
  color: map-deep-get($material-light, "text", "primary") !important;
}
```
