### ISSUE TITLE
[Bug Report] v-divider (inset) use margin instead of max size and remove space.

### ISSUE THREAD

**Issue by infacto** [vuetifyjs/vuetify#12054]
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.125
**OS:** Windows 10

### Steps to reproduce
1. Create a layout with a grid. 
2. Add divider.
3. See that divider takes space and forces wrapping layout. Remove space with negative margin.
4. See that the max-width / max-height calculation does not work correctly. Use margin instead.

### Expected Behavior
It's possible to remove the space of a border in this case of a line divider. Could be an option.

### Actual Behavior
The border takes space and breaks by layout. Removing that space results in a wrong compution of max-width / max-height.

### Reproduction Link
<a href="https://codepen.io/infacto/pen/rNexgJN" target="_blank">https://codepen.io/infacto/pen/rNexgJN</a>

### Other comments
Regardless of my case, consider to use margin only without max-width / max-height.
What do you think about? I think this is a more solid solution.
And removing space by negative margin also could be a great solution. Maybe as option (attribute like `inset`). 

#### My Steps

**Without any hacks**
![1-without-hacks](https://user-images.githubusercontent.com/60390085/90229343-0ef8f700-de18-11ea-85eb-95d160cd3a7d.png)

**Remove space.**
![2-hack-remove-space](https://user-images.githubusercontent.com/60390085/90229355-115b5100-de18-11ea-8490-b4baf5f5a158.png)

**Use margin instead of max-width / max-height**
![3-hack-use-margin](https://user-images.githubusercontent.com/60390085/90229363-13251480-de18-11ea-969e-0ddd4e491eaa.png)

#### My final SCSS

```scss
.v-divider--inset {
  max-width: initial !important;
  max-height: initial !important;
  &:not(.v-divider--vertical) {
    margin-top: -1px !important;
    margin-left: 8px !important;
    margin-right: 8px !important;
  }
  &.v-divider--vertical {
    margin-left: -1px !important;
    margin-bottom: 8px !important;
  }
}
```

This only adds some styles to the build-in styles of Vuetify.
For example: Margin left and top is already set that framework.
So, set all styles in the final solution to have complete styles.

I like Vuetify and value you expert opinion. Margin only (without max-size) is a more solid way to do that, or not? And divider without spaces are more flexible to use in layout. What do you think about?
