### ISSUE TITLE
[Feature Request] gradient colors in the theme definition 

### ISSUE THREAD

**Issue by mohamedamjad** [vuetifyjs/vuetify#12166]
### Problem to solve
Be able to define a gradient as primary color.

**Comment by KaelWD** [comment]
Gradients are only usable as `background-image`, theme colours need to be able to work as `color` and `border-color` too.

**Comment by kissu** [comment]
Hi! I'm not on the Discord but is this feature definitely closed and will not be implemented (in 2022)?

A question is asked regarding that subject: https://stackoverflow.com/q/73895844/8816585

**Comment by frederikheld** [comment]
@KaelWD Your answer is very much focused on the current technical solution. And although I understand that it is not easy to change the current approach, it doesn't really help with the question to just say "it's not possible" and close it. You could at least consider it as a feature for future releases.

@mohamedamjad @kissu Here's my approach to theme color gradients with Vuetify 3. I define gradient variables that are being derived from the theme colors in `App.vue`.

You can use them to create gradient classes that you can then apply on the elements you want to use them for or you an apply the gradients directly to the component classes. It is a bit more manual work than just changing colors in the template, but after you have done it, the gradients automatically change with the theme colors, so theme switching is supported:

```css
:root {
  --gradient-primary: linear-gradient(
      100deg,
      color-mix(in srgb, rgb(var(--v-theme-primary)) 70%, #000 30%),
      rgb(var(--v-theme-secondary)),
      color-mix(in srgb, rgb(var(--v-theme-primary)) 90%, #000 10%),
      rgb(var(--v-theme-secondary)),
      color-mix(in srgb, rgb(var(--v-theme-primary)) 70%, #000 30%)
    );
}

/* Apply gradient as text color */
.gradient-text-primary {
  background: var(--gradient-primary);
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

/* Apply gradient as background color */
.v-btn.bg-primary,
.gradient-surface-primary {
  background: var(--gradient-primary) !important;
}
```

It works well for the metallic effect gradient that I am using here which just varies the brightness of one single theme color. But it might be possible to set different gradient colors in the theme and use them in the gradient variable where I use `color-mix`.

I hope this helps.
