### ISSUE TITLE
[Feature Request] Allow sizing in arbitrary units, like rems

### ISSUE THREAD

**Issue by matthew-dean** [vuetifyjs/vuetify#12532]
### Problem to solve
Allows Vuetify components to be responsive

### Proposed solution
For a component like V-Btn, some items, like `$btn-font-sizes` allow setting units, which is great. However, maps like `$btn-sizes` are specified in integers, and then forced into `px` units in `VBtn.sass`.

Ideally, buttons could be defined like:
```scss
$btn-sizes: (
  'x-small': 3rem,
  'small': 4rem,
  'default': 5rem,
  'large': 6rem,
  'x-large': 7rem
);
```
And then this would scale perfectly with something like:
```scss
html {
  font-size: 8px;

  @media (min-width: 768px) {
    font-size: 10px;
  }
}
```

As it is right now, Vuetify components don't scale proportionally to different devices because of fixed pixel values.
