### ISSUE TITLE
[Feature Request] v-tooltip with arrow to emphasize direction

### ISSUE THREAD

**Issue by timothymarois** [vuetifyjs/vuetify#12939]
### Problem to solve
This feature would improve user experience (UX) and help with giving the right direction to the tip being show. Currently, there is no direction, and after thousands of user tests we've run across our platforms, we've noticed that user's believe the tooltips are the buttons instead of telling the user what the button actually does. This is because the tooltip themselves look as if they are independent from their original object.  

### Proposed solution
Like many tooltips across many online packages, they usually always have an arrow pointing towards its object. Most notably, the [Bootstrap tooltip](https://getbootstrap.com/docs/4.0/components/tooltips/). 

**Example with tooltip and arrow**

<img width="159" alt="Screen Shot 2021-01-10 at 9 11 20 PM" src="https://user-images.githubusercontent.com/2489333/104142312-10a7f600-5389-11eb-9cc6-ad48577b1a91.png">

**Compared to what it currently does:** 

This is just one example of many, for the user's its hard for them to understand the tooltip is a helpful guide rather than the button they should click. Especially if you activate tooltips without hover, its even more confusing towards users, 78% of the sample of users tested clicked the tooltip message instead of the buttons themselves. 

<img width="155" alt="Screen Shot 2021-01-10 at 9 17 15 PM" src="https://user-images.githubusercontent.com/2489333/104142386-641a4400-5389-11eb-8463-7c988a4e5361.png">

**Comment by kylawamg** [comment]
+1

**Comment by alexdarh** [comment]
+1

**Comment by mchl18** [comment]
1+
At least let us attach some class to the actual tooltip

**Comment by jacekkarczmarczyk** [comment]
@mchl18
> At least let us attach some class to the actual tooltip

use `content-class` prop

**Comment by justinehell** [comment]
+1

**Comment by abepetrillo** [comment]
Any update on this? Hit the same requirement

**Comment by Hextar** [comment]
Using content-class I've been able to add a class 'right-arrow' to position a pseudo-element accordingly.
More classes could be used depending on which is the tooltip positioning and the desired arrow direction (top-left, top-center, top-right, etc)

```scss
	$arrow-height: 16;
	$arrow-width: 16;

	.v-tooltip__content.menuable__content__active {
		&.right-arrow {
			display: flex !important; // that's important to make the pseudo-element visible outside the main container
			overflow: inherit !important; // that's important to make the pseudo-element visible outside the main container
			z-index: 20;

			&::before {
				content: '';
				position: absolute;
				width: #{$arrow-width}px !important;
				height: #{$arrow-height}px !important;
				top: calc(50% - #{$arrow-height / 2}px);
				bottom: 0;
				right: -#{$arrow-width}px;
				z-index: 21;
				// custom appearance rules
			}
		}
	}
```
