### ISSUE TITLE
[Bug Report] v-select: multiple,chips, dense, outlined - Chips overlap with label

### ISSUE THREAD

**Issue by sugoidesune** [vuetifyjs/vuetify#13107]
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.150
**OS:** Windows 10

### Steps to reproduce
Set v-select to multiple, chips, dense, outlined.
Select an option. 

### Expected Behavior
Chip is resized to fit dense v-select.

### Actual Behavior
![image](https://user-images.githubusercontent.com/20317691/107923122-54d27b80-6f71-11eb-92be-0de2c74b987f.png)
Chip overlaps with Label.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/selects/#multiple" target="_blank">https://vuetifyjs.com/en/components/selects/#multiple</a>
The example in the docs works to test it. just add the flags "dense outlined"

### My solution for now
```css
.v-input--dense.v-text-field--outlined .v-chip {
  height: 24px;
  margin-top: 5px;
  padding-left: 9px;
  padding-right: 9px;
}
```
