### ISSUE TITLE
NPM package 0.14.10 corrupted

### ISSUE THREAD

**Issue by SquareBeard** [vuetifyjs/vuetify#1339]
The css file within the dist folder contains errors in the following archive: https://registry.npmjs.org/vuetify/-/vuetify-0.14.10.tgz

Here is a small sample:
```css
subheading {
  color: #424242;
  font-size: 16px;
  font-weight: 400;
  line-height: ;
  letter-spacing: ;
  margin-bottom: 16px;
}
```

As you can see the line-height and letter-spacing are invalid.
The file is not minified either.
