### ISSUE TITLE
[Feature Request] ltr & rtl mixin doesn't work for v-application

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13987]
### Problem to solve
Currently If I want to give style using selector added along with `.v-application` then I am unable to use `ltr` and `rtl` mixin because it generate styles like below:

```scss
.v-application {
    &.layout-horziontal-nav {
        @include ltr() {
            padding-left: 64px; // random style and vaule
        }
        @include rtl() {
            padding-right: 64px; // random style and vaule
        }
    }
}
```

> Output
```css
.v-application--is-ltr .v-application.layout-horizontal-nav { ... }
.v-application--is-rtl .v-application.layout-horizontal-nav { ... }
```

### Proposed solution
`ltr` & `rtl` mixins should handle top-level selectors as well like above.

**Comment by KaelWD** [comment]
I don't know if this even can be fixed. Very simple workaround is to just use the classes here instead:

```css
.v-application {
    &.layout-horizontal-nav {
        &.v-application--is-ltr {
            padding-left: 64px;
        }
        &.v-application--is-rtl {
            padding-right: 64px;
        }
    }
}
```

Or use [CSS logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) if you only have to support modern browsers.
