### ISSUE TITLE
[Feature Request] Themed Scrollbar & Webpage Overscroll Background

### ISSUE THREAD

**Issue by gauthamkrishna9991** [vuetifyjs/vuetify#14039]
#### **1.** Themed Scrollbar (`html { scrollbar-color }`)

The new CSS Property [`scrollbar-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) in the `html` component now takes care of the webpage scrollbar color (presently supported by *Mozilla Firefox* (85+), *Chromium* (Google Chrome (partly implemented, slated for 94+) and *Microsoft Edge* (partly implemented)), and *Safari* (15+) would also end up supporting the same), it would make Vuetify Apps look a lot more native to a browser, and would look more native for the same.
[`scollbar-color` in MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color)

#### **2.** Webpage Over-scroll Background (`html { background-color }`)

Since a lot of laptop browsers use touchpads to scroll, and since a lot of browsers also support the overscrolling feature (whose overscroll background colors are taken care of by `background-color` property in `html` object), it would also benefit Vuetify to theme the `background-color` property to look more native for Browsers on Touchpad inputs or Touchscreens.
```css
html {
  scrollbar-color: #616161 #121212;
  /* Supporting the new "scrollbar-color" CSS property for CSS, which is supported by Firefox, Chrome, Edge and Safari.*/
  background-color: #121212; 
  /*This background color is used to color over the parts of page when one overscrolls a web-page, most times when users use touchpads on Laptops or touchscreens.*/
}
```

#### **1.** Themed Scrollbar

Update SASS/SCSS Variables to support the `scrollbar-color` property on `html` object to natively support the themed scrollbar feature. This feature is currently fully supported in Firefox 90+ (test on Fedora 34 on x86_64), and full support for other browsers are either presently being implemented (Safari) or is partly implemented (Chromium).

#### **2.** Webpage Overscroll Background

The CSS Property of `background-color` for `html` object is responsible for coloring the overscroll backgrounds presently, so updates to the SASS/SCSS variables to support the same is also what I'd prefer to see..

[An Example for Themed (Dark) Scrollbars (HARD-CODED)](https://codepen.io/gauthamkrishna9991/pen/yLbQGPj?editors=0100). Please check this out in Firefox (89+, preferably in Linux, but MacOS or Windows also works, hopefully).
