### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] v-btn has always a shadow even with text and flat

### ISSUE THREAD

**Issue by HippolyteQuief** [vuetifyjs/vuetify#14303]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Last working version:** 3.0.0-alpha.10
**Vue Version:** 3.2.20
**Browsers:** Chrome 94.0.4606.81
**OS:** Windows 10

### Steps to reproduce
Just use a button and try to remove shaddow. `flat`, `text`, `elevation="0"` or `box-shadow: none !important` doesn't remove anything. Their is now this rule adding the box-shadow
``` css
.v-btn--variant-contained::before {
box-shadow: 0px 3px 1px -2px rgb(0 0 0 / 20%), 0px 2px 2px 0px rgb(0 0 0 / 14%), 0px 1px 5px 0px rgb(0 0 0 / 12%);
}
```

### Expected Behavior
Having no shadow

### Actual Behavior
Their is always a shadow

### Reproduction Link
<a href="https://codepen.io/QuiefH/pen/RwZGRmJ" target="_blank">https://codepen.io/QuiefH/pen/RwZGRmJ</a>
