### ISSUE TITLE
[Bug Report][2.5.14] Cannot use position: fixed in VTabs

### ISSUE THREAD

**Issue by LazyLZ** [vuetifyjs/vuetify#14439]
### Environment
**Vuetify Version:** 2.5.14
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
Set position:fixed for the child elements of VTab

### Expected Behavior
Element positioning according to window

### Actual Behavior
element position is act like absolute

### Reproduction Link
<a href="https://codepen.io/lazylz/pen/KKvOvQo?editors=101" target="_blank">https://codepen.io/lazylz/pen/KKvOvQo?editors=101</a>

### Other comments
I tried to implement a draggable tab component, so I needed to set the `position` of the tab to `fixed` to make it follow the cursor, but it did not work.
I found this happened because the style in `v-slide-group__wrapper` class, it set `contain` to `content`

```css
.v-slide-group__wrapper {
    contain: content;
    display: flex;
    flex: 1 1 auto;
    overflow: hidden;
}
```

I can't figure out why this property is set, and it's not supported by safari either.
