### ISSUE TITLE
Menu activator buttons inside toolbar items do not get properly styled.

### ISSUE THREAD

**Issue by onimatrix81** [vuetifyjs/vuetify#1506]
### Steps to reproduce
Create a toolbar with buttons as toolbar-items, create another button that is in activator slot of a menu.

### Versions
Vuetify 0.14.11

### What is expected ?
The button inside the activator should be styled the same as bare buttons, ie. 100% height and no margins.

### What is actually happening ?
The button inside the menu activator slot does not get styled.

### Reproduction Link
https://codepen.io/froller/pen/rzqmZP

### Workaround
User Sys0 on Discord provided following CSS to work around the problem for now.
```css
.toolbar .menu__activator { height: 100% }
.toolbar .menu__activator .btn { margin: 0; height: 100% }
```
