### ISSUE TITLE
menu from toolbar partly hidden when toolbar is fixed

### ISSUE THREAD

**Issue by miquels** [vuetifyjs/vuetify#151]
As debugged on gitter, a v-menu on a v-toolbar that is fixed opens under the toolbar instead of on top of it. Adding this CSS in e.g. App.vue fixes it:

```css
.toolbar--fixed {
  z-index: 3 !important;
}
```
