### ISSUE TITLE
[v0.15.0-beta.4] v-text-field pt-0 single-line messes up input label

### ISSUE THREAD

**Issue by roblav96** [vuetifyjs/vuetify#1514]
### Steps to reproduce
```html
<v-text-field class="pt-0" label="Format timestamp..." single-line></v-text-field>
```
By default the input field has a `padding-top` which is undesirable and adding `pt-0` to the input field messes up the label.

### Versions
v0.15.0-beta.4

### What is expected ?
Label to be centered with input field.

### What is actually happening ?
![img](http://i.imgur.com/1yUeXeg.png)

### Temporary fix
```css
div.input-group--single-line > label {
    top: initial;
}
```
