### ISSUE TITLE
icon color in active list item in drawer menu differs from text color

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1519]
### Steps to reproduce
Create router menu and set route or hover on link

### Versions
Vuetify 0.15.0-beta.4
Vue 2.4.2

### What is expected ?
Icon should be blue (same color as text)

### What is actually happening ?
Icon has default color

### Reproduction Link
https://codepen.io/wernerm/pen/LjggoV

Edit: shouldn't be blue if the icon is inside the button
https://codepen.io/anon/pen/YxRPvR

**Comment by johnleider** [comment]
This is something that is not covered in spec and currently is just my interpretation. I think this is something we should discuss to come up with the best handling of color for the various situations that are possible.

**Comment by wernerm** [comment]
At the moment I'm getting around this by adding two simple CSS rules to the component where a `v-list` is used:

```css
.list__tile--active .list__tile__action,
.list__tile--active .list__tile__action .icon {
  color: inherit;
}
```

Maybe it would be nice if this behaviour was configurable via a new `v-list` prop?
