### ISSUE TITLE
[Feature Request] Make style class of 'gap'

### ISSUE THREAD

**Issue by hslee2008** [vuetifyjs/vuetify#15282]
### Problem to solve
When using row, column, flex, grid, we need the attribute `gap`.
This does not exist in Vuetify and can help a lot of people with this class.

### Proposed solution
`gap-` or `g-` with numbers after it to set the gap.

**Comment by MaximumRGB** [comment]
That could be really helpfull!

**Comment by karwan01** [comment]
that would be helpful

**Comment by MetRonnie** [comment]
SCSS implementation:
```scss
@for $i from 0 through 16 {
  .row-gap-#{$i} {
    row-gap: $i * 4px;
  }
  .col-gap-#{$i} {
    column-gap: $i * 4px;
  }
  .gap-#{$i} {
    @extend .row-gap-#{$i};
    @extend .col-gap-#{$i};
  }
}
```
