### ISSUE TITLE
[Bug Report][3.0.0] v-checkbox long label not wrapped on small container

### ISSUE THREAD

**Issue by trikarai** [vuetifyjs/vuetify#15708]
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Last working version:** 2.6.2
**Vue Version:** 3.2.13
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. v-col cols="2"
2. v-checkbox
3. add very long label

### Expected Behavior
label wrap

### Actual Behavior
label not wrap

### Reproduction Link
<a href="https://codepen.io/trikarai/pen/jOzgmeX" target="_blank">https://codepen.io/trikarai/pen/jOzgmeX</a>

**Comment by KaelWD** [comment]
```css
.v-checkbox .v-selection-control {
  /* height: var(--v-input-control-height); */
  min-height: var(--v-input-control-height);
.v-selection-control .v-label {
  /* height: 100%; */
  white-space: normal;
  word-break: break-word;
.v-selection-control--inline {
  min-width: 0;
  max-width: 100%;
}
```
