### ISSUE TITLE
[Bug Report][3.0.0-beta.15] VSelect height changes between empty and non-empty states when using `chips`

### ISSUE THREAD

**Issue by aentwist** [vuetifyjs/vuetify#15980]
### Environment
**Vuetify Version:** 3.0.0-beta.15
**Vue Version:** 3.2.41
**Browsers:** Firefox 105.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. use VSelect
1. use `chips`

### Expected Behavior
no height change

### Actual Behavior
height change

### Reproduction Link
[https://codepen.io/aentwist/pen/xxzbqxz](https://codepen.io/aentwist/pen/xxzbqxz)

### Other comments
I was able to fix this by letting flexbox do the work instead of calculating dimensions,

```css
.v-select .v-field__input {
  padding-top: 0;
  padding-bottom: 0;
  align-items: center;
}
```

The chips are off-center too, due to this. Maybe the alignment should be redone.

```css
.v-select--chips .v-select__selection {
  margin-top: 2px;
}
```
