### ISSUE TITLE
[Bug Report][3.0.4] v-tab height styles conflict with v-btn

### ISSUE THREAD

**Issue by codeflorist** [vuetifyjs/vuetify#16254]
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10, Linux

### Steps to reproduce
1. Install Nuxt 3 and Vuetify 3
2. Add Treeshaking according to https://next.vuetifyjs.com/en/features/treeshaking/
3. Add a `v-tabs` element

### Expected Behavior
The buttons should have their height adapted to the height of the v-tab component.

### Actual Behavior
The tab-buttons have their height reduced.

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-ker2ba?file=app.vue](https://stackblitz.com/edit/nuxt-starter-ker2ba?file=app.vue)

### Other comments
In an installation without treeshaking, the following CSS is present:
```css
.v-tab {
    --v-btn-height: var(--v-tabs-height);
}
```
With treeshaking this CSS is missing, thus `--v-tabs-height` falls back to this definition:
```css
.v-btn--size-default {
    --v-btn-height: 36px;
}
```
This results in the wrong height.
