### ISSUE TITLE
[Feature Request] Optional column dividers for v-table

### ISSUE THREAD

**Issue by matthiashermsen** [vuetifyjs/vuetify#16336]
### Problem to solve
This is a duplicate of https://github.com/vuetifyjs/vuetify/issues/3364

*This feature might already be implemented but I wasn't able to find it in the docs yet => https://next.vuetifyjs.com/en/api/v-table/*

Adding a vertical divider to table columns ( `th` and `td` ) clearly separates them, if needed.

### Proposed solution
Adding an optional attribute `vertical-lines:false` which adds a left border to each column except the first one.

As already mentioned in #3364 `grid-lines:false` might also be an option to apply borders to the whole table.

---

Custom CSS solves the problem

```css
table th + th { border-left: 1px solid #dddddd; }
table td + td { border-left: 1px solid #dddddd; }
```

but package updates, custom colors, light/dark mode etc. might break it.

---

This feature exists for Vuetify 2 ( https://vuetifyjs.com/en/api/v-data-table/#props-headers ) but this only works for `v-data-table`, not for "raw" tables
