### ISSUE TITLE
[Feature Request] Use CSS Variables for styling to remove need for recompiling SCSS

### ISSUE THREAD

**Issue by sugoidesune** [vuetifyjs/vuetify#16599]
### Problem to solve
Customizing Vuetify has since Vuetify2 been cumbersome to implement and extremely slow as it recompiles all SCSS in all components used or unused, on each change to to the variables or nuxt.config
With build times reaching minutes. Unfortunately this hasn't been adressed in Vuetify3, with any performance improvements coming not from Vuetify 3 but from projects like Vite. It even comes with a wall of warnings:
![image](https://user-images.githubusercontent.com/20317691/217140382-6d553c02-1d2f-4285-a2aa-c8fb0bfb9c64.png)

### Proposed solution
Using CSS Variables should remove the need recompile.
```scss
// instead of this
$button-height: 40px,
button {
height: $button-height
}
```
Vuetify could use this:
```scss
:root {
--vuetify-default-button-height: 40px;
//customized
--vuetify-button-height: 37px;
}

button {
// CSS variables support fallback
height: var(--vuetify-button-height, --vuetify-default-button-height);
}
```
This allows for deep customization without recompiling or complicated implementation steps.
And should for the majority of projects remove the need to recompile vuetify.
