### ISSUE TITLE
[Bug Report][3.3.14] Content in centered horizontal timeline is off the center

### ISSUE THREAD

**Issue by KazimirPodolski** [vuetifyjs/vuetify#18176]
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Use a timeline with `direction="horizontal"` and default `align="center"`.
2. See the content shifted from the center of the icon.

Reproduces in on v-timeline's page in the docs in the very first example.

### Expected Behavior
The content is centered.

### Actual Behavior
The content seems to be off 24px.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVDtuGzEQvcqAtbhE4CCFoAQO0gbIAbwu6OXEnoS/kLObj6G7Z7gr2yupsGvDJd/MvF/Bq3v1OeduGlFt1Y4xZG8ZP/URYDdppoCeIoKjggNTih97dZcK/UuRre/VvHi0qklIDrAMHhhh0tUn3qacU5WVxw2AbwcIBiHFyI+35sjODDmaVpftCYO3tYotxj+s7z6Ipy8LDzCxx505ucmrB8DXVDAA5ToGcMmnAmIFbEDeND9VUiOPBayjTHWgeAsSU4YVnRwA0lhDctCsyjHFgRy5UdRHBm9vhB6QF2qEYG+jBevp12i7lSfzZGrtd2fOe30r/K3w1134MSrAqia1UQL+rN2PmqL8WPdtvVdDrb3awtVCKl8Uc65bYwYXZdMJ0VS6iGxiDkb+Oqbvfy8vuovu3XsxU/kB05KndjNbo7ru414UqQVnHWw+kV0Gs/SMNEyY2vsZD5eyZoqUKCm1S2E2c/CygjusQd+U9LtiEZJebVYyzfALpJ6NKxpn3EYEJyy6YHRYsLw00snZOtbJ6CxaU9+3wvcbNZ9J84tndf0fMpAsEQ==)

### Other comments
Disabling rule
```css
.v-timeline--horizontal.v-timeline .v-timeline-item__body, .v-timeline--horizontal.v-timeline .v-timeline-item__opposite {
  padding-inline-end: 24px;
}
```
seems like fixing it.
