### ISSUE TITLE
support flex-direction: column for the layout grid section and equal column heights

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#182]
Hi,

I was playing around to support equal heights over multiple columns. My first impression is, that only small changes needs to be done for supporting this.

Example for 2-column element where the first column has tall height and is scrollable inside, the second stretches to the same height as the first column:
http://codepen.io/anon/pen/YZpvvj

Example of top toolbar, main content and footer:
http://codepen.io/anon/pen/PpbyWy

Example of top toolbar, main content, footer and left-sidebar
https://codepen.io/anon/pen/MpbPoa

Example of top toolbar, main content, footer and fixed-left-sidebar
https://codepen.io/anon/pen/PpbyEX

Example of top toolbar, main content 2-column, footer and fixed-left-sidebar
https://codepen.io/anon/pen/NpbePa

Requirements for making this work is, to limit first the body, html to 100% of the height.
```css
/* required otherwise the body will scroll */
body, html {
    height: 100%;
    min-height: 100%;
    overflow: hidden;
    max-width: 100%;
    max-height: 100%;
}

/* set any element scrollable */
.scrollable {
    overflow: auto;
}

/* column for flex direction */
.layout-column {
    box-sizing: border-box;
    display: flex;
    height: 100%;
    width: 100%;
    flex-direction: column;
}

/* stretches the current element */
.flex {
    display: flex;
    flex: 1;
}
```

```javascript
// simple functional component for showing a div with class="layout-column"
const Column = {
  functional: true,
  render: (h, { data, children }) => {
      data.staticClass = data.staticClass ? `layout-column ${data.staticClass}` : 'layout-column'
      return h('div', data, children)
    }
}
```
