### ISSUE TITLE
Box text field focuses only when clicked on input

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1829]
### Steps to reproduce
Create `<v-text-field box>` as in codepen, try to focus the input by clicking the field outside the blue area

### Versions
0.15.7

### What is expected ?
Clicking the box field in any place (with pointer cursor) should focus the input

### What is actually happening ?
Input focuses only when the blue area is clicked (although the hover area is bigger)

### Reproduction Link
https://codepen.io/anon/pen/aLZJVP

**Comment by nekosaur** [comment]
This also applies to textarea inputs

**Comment by peluprvi** [comment]
Codepen for textarea (cliking on the blue area works):
https://codepen.io/anon/pen/ooNMaM

**Comment by nkovacs** [comment]
Normal input fields also have the same problem when the label is transformed, i.e. when the input is not empty or it has a placeholder.

**Comment by nkovacs** [comment]
Textareas can be fixed using this css:
```scss
.input-group--text-field.input-group--textarea:not(.input-group--full-width) .input-group__input {
    padding: 0;
    textarea {
        padding: 30px 0 0 13px;
    }
}
```

The other inputs can also be fixed in a similar way, extending their click area to the label's (transformed) position, e.g.: 
```scss
.input-group--text-field:not(.input-group--select):not(.input-group--single-line):not(.input-group--text-field-box):not(.input-group--textarea) {
    padding-top: 0; // original is 18px

    input {
        height: 48px;
        padding-top: 18px;
    }

    textarea {
        padding-top: 18px;
    }

    .input-group--text-field.input-group--multi-line textarea {
        padding-top: 22px;
    }
}
```

Or with something like this: https://github.com/nkovacs/vuetify/commit/9d0c164a3718521b43fb8dffd32fe8981934eff1
