### ISSUE TITLE
[Feature Request] Ability to hide eye-dropper in `VColorPicker`

### ISSUE THREAD

**Issue by yimme** [vuetifyjs/vuetify#19150]
### Problem to solve
There is currently no native way to disable the eye-dropper in the color picker component.
I had to disable it for a project by using 
```css
.v-color-picker-preview__eye-dropper {
    display: none !important;
}
```

### Proposed solution
Add a `hideEyeDropper` prop on `VColorPicker` that will prevent it from being rendered.

I can make a PR for this if its wanted.
