### ISSUE TITLE
[Feature Request] V-Timeline-Item property for left and right equals to v2

### ISSUE THREAD

**Issue by mthoer** [vuetifyjs/vuetify#19363]
### Problem to solve
Allow to apply specific styling depending on which side the opposite is located along the timeline

### Proposed solution
Provide a boolean left or right which indicates on which side the slot is going to be rendered.

In the the documentation of the v2 https://v2.vuetifyjs.com/en/api/v-timeline-item there are properties for "left" and "right" to handle manuel the orientation of the time-line-item.

**Comment by mthoer** [comment]
?

**Comment by mthoer** [comment]
This is a friendly reminder @KaelWD @MatthewAry @webdevnerdstuff

**Comment by mthoer** [comment]
Can you tell me if there is a time frame in which I can expect the feature?

**Comment by Dress13** [comment]
Hello, I have the same wish. This feature is also very important to me. Determining the alignment of the items (by left and right) was a big advantage in version 2. Is there a chance to integrate this property again?

Thank you very much :)

**Comment by mthoer** [comment]
Will we also get feedback here? It's a real shame to be left hanging like this and not get any further statements

**Comment by J-Sek** [comment]
Workaround ([demo](https://play.vuetifyjs.com/#eNqdUttu2zAM/RXOGJANi5Km25OXDtjjvqEuGs3SXKKyLEh00Czzv4+Sk1ZJGvTy4lDn8JA8ZK63RfD1/Kdzs3Wvi7JYkm6dkaR/VBZguRbSOaA73eqrqlDS31dFYhJXd5YkWu13UAIJW20YfMQOUIHc4IkBWIs/nefanyIxBfwMaCHGoSryvPJebzgNj9DayBAYXx21ECKg0uLjNj5mMR5Wh9KAf6OnBxFaaUzOZZOPNqVX3KkzadBUMD2qAkpCMrHM6hfDwO3gCywG+BfDvDPM833Mj6Z92l/G7PfM0OGiI8Jn4Xg5z87Fz1B7dARBUx9pABYGGtcJV3A9Vtyyd6VLmASSniZTzmI3/G681lYYbO6IfxcTGKYvKNAqbLpHyeUzEm1VJvBavSHb9d4ZfSq4idZHszvjtDHjwmbZasVae8JaGtiObXIy+5ckVyfk7e3vTm12A55R8rjP6DrnusDhvi1A41HxFU3f2hIW8AFb13mSlr7vM5xUCm0j0MZCJVzA5Tf3cJo5vMvJfqL3uIlbOOPk62ucJB8XZ5zwhy+5u14xTG1vTPrc/Ac0Mnrf)) until PR get's merged:

```html
<v-timeline-item :class="`v-timeline-item--side-${item.side}` />
```

```css
/* :class="`v-timeline-item--side-${item.side}`" */
.v-timeline--vertical {
  .v-timeline-item--side-start .v-timeline-item__body,
  .v-timeline-item--side-end .v-timeline-item__opposite {
    grid-column: 1 !important;
    padding-inline: 0 24px !important;
  }
  .v-timeline-item--side-start .v-timeline-item__opposite,
  .v-timeline-item--side-end .v-timeline-item__body {
    grid-column: 3 !important;
    padding-inline: 24px 0 !important;
  }
}
```

(for `--horizontal` replace `grid-column` with `grid-row` and `padding-inline` with `padding-block`)
