### ISSUE TITLE
[Feature Request] Prevent overflow in mobile data tables

### ISSUE THREAD

**Issue by donalmurtagh** [vuetifyjs/vuetify#19781]
### Problem to solve
If the content of a mobile data table cell is too long, it breaks the layout

### Proposed solution
The following style rule truncates the cell content to a single line when the data table is in mobile mode

```css
.v-data-table__tr--mobile .v-data-table__td-value {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

### [Demo](https://play.vuetifyjs.com/#eNrtUz1vgzAU/CtPLFkC7CmNlKEfQ7Z2ahJFD3gES45t2Q+SKMp/r8Gg0HbKXglh++58PuRjc42cLdKVMUnbULSIMqajkci03CqArI3RmH7aLwqtGIUiO0A9WCJjzJhLgoXw293zNurHbQRHnQtJyyydykY/D/407JBwXpZOcmSusMIwOOImhPHbHEN/CDzDJvhdx0wKj7SA2aqyokAFL5JMjYpn81HgDBWCnNes9VmXXQbAoMa7qhTEXvJONhettnRnaswFY0d+YItK4RxevcCxGzW3Yfyd6U1YrKqJ1RhlXAPMPmvhwD8ILdkLSK0O4NgKdUjgn3uce+xG11r5QsCX1tO7DLM0hSRJfKkthfJ18K5ra2io72bXVr4MHU+mrd/v2cZx+CH+MGXcomxo7Mup9vaxM1j40ih9smieAqP991VSnxZQi7IkNcBMZ47vHEkpjBOuZ299wCFUdJurRsr+tfsGlh9RIg==)
Remove the `<style>` element to see the problem without the solution

### API Proposal
The style rule above should be enabled by a boolean prop that is false by default in order to avoid making this a breaking change.
