### ISSUE TITLE
[Feature Request] Set table-header-font-weight to 700 as default

### ISSUE THREAD

**Issue by rauhur** [vuetifyjs/vuetify#19917]
### Problem to solve
Each heading title in each v-table and v-data table has a font-weight of 500, like the rest of the content. I consider this a problem as it does not allow to differentiate the headings from the content clearly.

### Proposed solution
Set `$table-header-font-weigh = 700 !default` at `src/components/VTable/_variables.scss` file

**Comment by david-burke-securian** [comment]
I was debugging this today. I think the problem is that if you are using Roboto as the font, then 500 weight appears bold. That's why all the examples on vuetifyjs.com have bold table headers. If the browser falls back to default sans serif (Arial in my case) then 500 does not appear bold, but 700 would. Unfortunately, 700 might be too much for Roboto, so I'm not sure what to suggest.

I was hoping to work around it by doing this, but it doesn't seem to work:

```js
const vuetify = createVuetify({
  defaults: {
    VDataTableHeaders: {
      style: 'font-weight: 700;',
    },
  },
});
```

A successful workaround is to add this to a global CSS file, but that seems like a bit of a hack and maybe too fragile if Vuetify updates style definitions in a future version:

```css
.v-table > .v-table__wrapper > table > tbody > tr > th,
.v-table > .v-table__wrapper > table > thead > tr > th,
.v-table > .v-table__wrapper > table > tfoot > tr > th {
    font-weight: 700;
}
```
