### ISSUE TITLE
[Feature Request] Support for Material Symbols

### ISSUE THREAD

**Issue by bun-lau** [vuetifyjs/vuetify#20053]
### Problem to solve
the new Material Icons collection is now "Material Symbols"

### Proposed solution
adding Material Symbols option/differentiate by icon name
updating the class name

**Comment by VIXI0** [comment]
i need this

**Comment by J-Sek** [comment]
Initially it looked like a good idea, until I actually integrated them and noticed that
- most of the icons have 6 variants "regular", "rounded", "sharp", "outline, "outline-rounded, "outline-sharp" - meaning the set is bloated, harder to lookup
- depending on the distribution they may be forced into distinct sets
- some symbols may be missing... it honestly feels like a beta release at the moment

You can actually use them today as aliases from "MD" set seem to work just fine.

```ts
import '@material-symbols/font-400/outlined.css'
import { aliases } from 'vuetify/iconsets/md' // aliases are the same
import { VLigatureIcon } from 'vuetify/lib/composables/icons.mjs'
import { h } from 'vue'
const mat = { component: (props: any) => h(VLigatureIcon, { ...props, class: 'material-symbols-outlined' }) }

import { createVuetify } from 'vuetify'

const vuetify = createVuetify({
  icons: {
    defaultSet: 'mat',
    aliases,
    sets: { mat },
  },
})
```

```html
<v-container class="d-flex flex-wrap ga-3" width="600">
  <v-btn variant='outlined' v-for='ic in Object.values(aliases)' :key='ic' :icon='ic' />
</v-container>
```

![image](https://github.com/user-attachments/assets/17128322-490e-4e65-8bdb-288c1a046317)

Apart from incorrect symbols for `$delimiter` and `$ratingFull` it seems good enough.

But it does not feel like the font is ready for official Vuetify support. I can only recommend using it through `nuxt-icons` that loads used symbols from `icones.js.org` and has access to the full set (includes filled stars)

**Comment by naffarn** [comment]
I was able to extend the iconset above with custom props, combined with some styling to allow you to use the axes via props on the icons.

Playground link: https://play.vuetifyjs.com/playgrounds/GTcf1g

```typescript
// materialSymbols.ts
import { h } from 'vue'
import type { IconSet, IconAliases, IconProps } from 'vuetify'
const aliases: IconAliases = {
  collapse: 'keyboard_arrow_up',
  complete: 'check',
  cancel: 'cancel',
  close: 'close',
  delete: 'cancel',
  // delete (e.g. v-chip close)
  clear: 'cancel',
  success: 'check_circle',
  info: 'info',
  warning: 'priority_high',
  error: 'warning',
  prev: 'chevron_left',
  next: 'chevron_right',
  checkboxOn: 'check_box',
  checkboxOff: 'check_box_outline_blank',
  checkboxIndeterminate: 'indeterminate_check_box',
  delimiter: 'fiber_manual_record',
  // for carousel
  sortAsc: 'arrow_upward',
  sortDesc: 'arrow_downward',
  expand: 'keyboard_arrow_down',
  menu: 'menu',
  subgroup: 'arrow_drop_down',
  dropdown: 'arrow_drop_down',
  radioOn: 'radio_button_checked',
  radioOff: 'radio_button_unchecked',
  edit: 'edit',
  ratingEmpty: 'star_border',
  ratingFull: 'star',
  ratingHalf: 'star_half',
  loading: 'cached',
  first: 'first_page',
  last: 'last_page',
  unfold: 'unfold_more',
  file: 'attach_file',
  plus: 'add',
  minus: 'remove',
  calendar: 'event',
  treeviewCollapse: 'arrow_drop_down',
  treeviewExpand: 'arrow_right',
  eyeDropper: 'colorize',
}

interface ExtendedIconProps extends IconProps {
  variant?: 'outlined' | 'sharp' | 'rounded';
  filled?: boolean | number | '';
  emphasis?: 'low' | 'default' | 'high';
}

const mds: IconSet = {
  component: (props: ExtendedIconProps) => {
    const variantClass = `material-symbols-${props.variant ?? 'rounded'}`
    const emphasisClass = props.emphasis
      ? `material-symbols-${props.emphasis}-emphasis`
      : ''
    const classes = {
      'material-symbols': true,
      [variantClass]: true,
      'material-symbols-filled': props.filled === '' || props.filled || false,
    }
    if (emphasisClass) {
      classes[emphasisClass] = true
    }
    // Set opsz from fontSize if one is supplied, i.e. by <v-icon size="32" />
    if (props.style?.fontSize) {
      const opsz = parseInt(props.style?.fontSize) || 24
      props.style['--md-icon-opsz'] = Math.min(Math.max(20, opsz), 48)
    }
    return h(props.tag, {
      ...props,
      class: classes,
      // style: `font-variation-settings: ${fontVariationSettings}`,
      innerHTML: props.icon,
    })
  },
}

export { aliases, mds }
```

Styles (probably not exhaistive, but near enough)

```css
:root {
  --md-icon-fill: 0;
  --md-icon-weight: 300;
  --md-icon-grad: 0;
  --md-icon-opsz: 24;
  --md-icon-transition-duration: 200ms;
  --md-icon-transition-easing: cubic-bezier(0.4, 0, 0.2, 1);
}

.material-symbols {
  font-variation-settings: 'FILL' var(--md-icon-fill), 'wght' var(--md-icon-weight), 'GRAD' var(--md-icon-grad), 'opsz' var(--md-icon-opsz);
  transition: font-variation-settings var(--md-icon-transition-duration) var(--md-icon-transition-easing), transform var(--md-icon-transition-duration) var(--md-icon-transition-easing);
}

/* Fill */
.material-symbols.material-symbols-filled {
  --md-icon-fill: 1;
}

/* Emphasis */
.material-symbols.material-symbols-high-emphasis {
  --md-icon-grad: 200;
}
.material-symbols.material-symbols-medium-emphasis,
.material-symbols.material-symbols-default-emphasis {
  --md-icon-grad: 0;
}
.material-symbols.material-symbols-low-emphasis {
  --md-icon-grad: -25;
}

/* Disable animation (or just remove this class, and the default animations) */
.material-symbols.no-animation {
  --md-icon-transition-duration: 0;
}

/* opsz */
.material-symbols.v-icon--size-x-small,
.material-symbols.v-icon--size-small {
  --md-icon-opsz: 20;
}
.material-symbols.v-icon--size-default {
  --md-icon-opsz: 24;
}
.material-symbols.v-icon--size-large {
  --md-icon-opsz: 28;
}
.material-symbols.v-icon--size-x-large {
  --md-icon-opsz: 32;
}

/* Automatically apply fill when items are selected in lists, tabs, and navigation */
.v-list-item--active i.v-icon.material-symbols,
.v-btn--active i.v-icon.material-symbols,
.v-tab--selected i.v-icon.material-symbols {
  --md-icon-fill: 1;
  --md-icon-grad: 200;
}

/* Disable fill animation in checkboxes */
.v-selection-control__input .v-icon.material-symbols {
  --md-icon-transition-duration: 0ms;
}
/* Apply fill to checked checkboxes */
.v-selection-control__input:has(input:checked:not([type='radio']))
  .v-icon.material-symbols {
  --md-icon-fill: 1;
}

/* Try to fix fill issues with ratings */
.v-rating__wrapper:has(~ .v-rating__wrapper input:checked)
  .v-icon.material-symbols,
.v-rating__wrapper:has(~ .v-rating__wrapper input:checked)
  .v-icon.material-symbols-outlined,
.v-rating__wrapper:has(~ .v-rating__wrapper input:checked)
  .v-icon.material-symbols-rounded,
.v-rating__wrapper:has(~ .v-rating__wrapper input:checked)
  .v-icon.material-symbols-sharp,
.v-rating__wrapper:has(input:checked) .v-icon.material-symbols,
.v-rating__wrapper:has(input:checked) .v-icon.material-symbols-outlined,
.v-rating__wrapper:has(input:checked) .v-icon.material-symbols-rounded,
.v-rating__wrapper:has(input:checked) .v-icon.material-symbols-sharp {
  --md-icon-fill: 1;
}

/* Fix fill issues with $delimiter alias in carousels */
.v-carousel__controls__item .v-icon {
  --md-icon-fill: 1;
}

```

**Comment by J-Sek** [comment]
Quick fix for v-rating half increments:

```css
.v-rating__wrapper:has(~ .v-rating__wrapper input:checked),
.v-rating__wrapper:has(input:checked) .v-rating__item--half {
  .v-icon[class*='material-symbols'] {
    --md-icon-fill: 1;
  }
}
```

**Comment by naffarn** [comment]
The above had a couple of issues like not filling the selected rating for the regular component, and filling the full star when the half rating is selected, but I've fixed it now to a place where i'm happy with it. The only issue I can see now is that for the half-increments a fully selected star has a slight color difference between the two halves:

<img width="26" alt="Image" src="https://github.com/user-attachments/assets/8a9355fd-0af8-4e93-9700-bcc96474ff30" />

Anyway, here's the updated styles. 
SCSS:
```scss
.v-rating__wrapper:has(~ .v-rating__wrapper input:checked), /* Fill ratings prior to the checked one */
.v-rating__wrapper:has(~ .v-rating__wrapper:hover), /* Fill ratings prior to the hovered one */
.v-rating__item:not(:has(.v-rating__item--half)):has(input:checked), /* Fill regular rating if it's checked */
.v-rating__item--half:has(~ input:checked), /* Fill half rating if it, or its full rating is checked */
.v-rating__item--full:has(+ input:checked), /* Fill full rating if it's checked */
.v-rating__item:not(:has(.v-rating__item--half)):hover, /* Regular, half & full ratings when hovered*/
.v-rating__item--half:hover,
.v-rating__item--full:hover {
  .v-icon[class*='material-symbols'] {
    --md-icon-fill: 1;
  }
}
/* When a rating is hovered, disable fill on subsequent selected stars */
.v-rating__wrapper:hover ~ .v-rating__wrapper,
.v-rating__item--half:hover ~ .v-rating__item--full {
  .v-icon[class*='material-symbols'] {
    --md-icon-fill: 0 !important;
  }
}
```
or plain CSS:
```css
.v-rating__wrapper:has(~ .v-rating__wrapper input:checked) .v-icon[class*='material-symbols'], /* Fill ratings prior to the checked one */
.v-rating__wrapper:has(~ .v-rating__wrapper:hover) .v-icon[class*='material-symbols'], /* Fill ratings prior to the hovered one */
.v-rating__item:not(:has(.v-rating__item--half)):has(input:checked) .v-icon[class*='material-symbols'], /* Fill regular rating if it's checked */
.v-rating__item--half:has(~ input:checked) .v-icon[class*='material-symbols'], /* Fill half rating if it, or its full rating is checked */
.v-rating__item--full:has(+ input:checked) .v-icon[class*='material-symbols'], /* Fill full rating if it's checked */
.v-rating__item:not(:has(.v-rating__item--half)):hover .v-icon[class*='material-symbols'], /* Regular, half & full ratings when hovered*/
.v-rating__item--half:hover .v-icon[class*='material-symbols'],
.v-rating__item--full:hover .v-icon[class*='material-symbols'] {
  --md-icon-fill: 1;
}
/* When a rating is hovered, disable fill on subsequent selected stars */
.v-rating__wrapper:hover ~ .v-rating__wrapper .v-icon[class*='material-symbols'],
.v-rating__item--half:hover ~ .v-rating__item--full .v-icon[class*='material-symbols'] {
  --md-icon-fill: 0 !important;
}
```
