### ISSUE TITLE
[Feature Request] Component - Sheets: side

### ISSUE THREAD

**Issue by darkbasic** [vuetifyjs/vuetify#20122]
### Problem to solve
Currently Vuetify is lacking Side sheet from Material Design Ui component. I would like to be able to use Side sheet component in my own projects. It would save me time if this is available in the UI components so I could quickly build my projects.

There was a [similar issue](https://github.com/vuetifyjs/vuetify/issues/5482) which has been closed in favor of `v-navigation-drawer`, but I don't think that's a viable alternative because of the lack of the `activator` slot. It would make for a bad pattern to implement most side sheets use cases.

### Proposed solution
Add [Sheets:side](https://material.io/design/components/sheets-side.html#) to Vuetify UI components (basically a `v-navigation-drawer` with the `activator` slot).
Alternatively just add the `activator` slot to `v-navigation-drawer`.
`v-bottom-sheet` covers a similar use case and has the `activator` slot.

**Comment by darkbasic** [comment]
Another reason why `v-navigation-drawer` is not up to the task: https://github.com/vuetifyjs/vuetify/issues/20128

**Comment by darkbasic** [comment]
Another issue with `v-navigation-drawer` is that sometimes it positions itself relative to its parent rather than the whole page:
![image](https://github.com/vuetifyjs/vuetify/assets/1047358/2868acee-fca4-47e6-8ded-14d6130367fb)

This doesn't happen with `v-bottom-sheet`.

**Comment by mirocklez** [comment]
It will add a lot of value - for filter sections, quick previews and etc. 👍

**Comment by darkbasic** [comment]
This is a quick and dirty CSS to transform `v-bottom-sheet` into `v-side-sheet` until it gets implemented in vuetify:
```css
.v-bottom-sheet > .v-bottom-sheet__content.v-overlay__content {
  left: unset !important;
  top: 0 !important;
  bottom: 0 !important;
  height: 100% !important;
  max-height: unset !important;
  width: 30% !important;
  max-width: unset !important;
}

.bottom-sheet-transition-enter-from {
  transform: translateX(100%) !important;
}
.bottom-sheet-transition-leave-to {
  transform: translateX(100%) !important;
}
```
