### ISSUE TITLE
[Feature Request] Combobox search

### ISSUE THREAD

**Issue by LeonSnajdr** [vuetifyjs/vuetify#20155]
### Problem to solve
If the selected item name is long, the search area is small, and it's quite hard to see my search term

### Proposed solution
Adding a flag to hide the current selected item and only showing the search.

**Comment by LeonSnajdr** [comment]
Currently, I fixed this by using custom CSS:

```css
.v-autocomplete__selection {
    display: none;
}
```
