### ISSUE TITLE
[Feature Request] Remove the fixed with of the VDataTable "Items per page" select

### ISSUE THREAD

**Issue by olivierpoisson** [vuetifyjs/vuetify#20212]
### Problem to solve
The fixed width of 90 px does not account for different languages than English. For the French language for example the "All" option is truncated and we only see one letter when selected.

The css style being applied:
```css
.v-data-table-footer__items-per-page > .v-select {
    width: 90px;
}
```

### Proposed solution
To remove the fixed with of 90 px so that the select can grow accordingly to the text of the option selected.
