### ISSUE TITLE
[Feature Request] V-slider: Disable clicking on the slider track

### ISSUE THREAD

**Issue by mrooding** [vuetifyjs/vuetify#20872]
### Problem to solve
We have a use case where we want to disable clicking on the v-slider's track. The only interaction allowed with the slider should be through moving the thumb around. 

### Proposed solution
Introduce a new disabled property that allows disabling the mouse down event on the slider track

**Comment by J-Sek** [comment]
Workaround:

```css
.v-slider__container { pointer-events: none; }
.v-slider-thumb { pointer-events: all; }
```
