### ISSUE TITLE
[Feature Request] Ripple Effect Disabled But Active State Styling Missing

### ISSUE THREAD

**Issue by cbkmutlu** [vuetifyjs/vuetify#21081]
#### Description
When I disable the ripple effect globally using the following configuration:

```js
export const vuetify = createVuetify({
   defaults: {
      global: {
         ripple: false
      },
   }
});

I no longer get the usual active state color feedback (such as the color change on :active state) on components like buttons (<v-btn>) and list items (<v-list-item>). This makes it difficult to visually detect that the button or list item has been clicked.

Currently, I am resolving this issue by manually applying the variant: "focus" property on individual components, like this:

```js
defaults: {
   global: {
      ripple: false
   },
   VBtn: {
      variant: "focus"
   }
}
```

And also adding the following custom CSS:
```css
.v-btn.v-btn--variant-focus:active > .v-btn__overlay {
   opacity: calc(var(--v-selected-opacity) * var(--v-theme-overlay-multiplier));
}
```

However, applying this fix manually for each component is not scalable.

### Proposed solution
It would be great if Vuetify could automatically add a class (e.g., v-ripple--false) to the <div class="v-application"> element or provide an easier way to manage the active state styling when ripple is globally disabled. This would allow us to manage the active state styles through CSS more efficiently, without having to manually configure each component.

Thank you!

```html
<div class="v-application v-theme--light v-layout v-layout--full-height v-locale--is-ltr v-ripple--false">
```

**Comment by 3dyuval** [comment]
For anyone wanting this behavior
1. disable v-ripple
```ts
createVuetify({
   defaults: {
   global: {
   ripple: false    // To disable globally
  },
   VListItem: {
     ripple: false   // Enable/disable specific component
   }
  }
 })
```

2. Add the effect
```scss
// Add the effect as cbkmutlu did
.v-btn.v-btn--variant-focus:active > .v-btn__overlay {
   opacity: calc(var(--v-selected-opacity) * var(--v-theme-overlay-multiplier));
}

// Or add list of elements to apply a default pressed state to 
@each $el in '.v-btn' '.v-list-item' {
  #{$el}:active > #{$el}__overlay {
      opacity: calc(var(--v-selected-opacity) * var(--v-theme-overlay-multiplier));
    }
}

```

I hope this workaround is temporary
