### ISSUE TITLE
[Feature Request] VDatePicker: Distinguish out-of-range dates versus allowed dates

### ISSUE THREAD

**Issue by chriscarrillo** [vuetifyjs/vuetify#21285]
### Problem to solve
When using the `min` and `max` props with `allowed-dates`, any date that isn't selectable, whether because it falls outside the range or because `allowedDates(date)` returns `false`, is rendered with the same "disabled" style. This makes it impossible to differentiate visually:
- **Out-of-range** (`< min` or `> max`)
- **In-range but not allowed** (within `min`/`max`, but filtered out by `allowed-dates`)

You can observe [the allowed-dates example in the VDatePicker Vuetify documentation](https://vuetifyjs.com/en/components/date-pickers/#allowed-dates).

### Proposed solution
Have `v-date-picker` apply two separate CSS classes (and document them) so consumers can target each case:
1. **Dates outside** `min`/`max`
- Class: `v-date-picker-date--out-of-range`
2. **Dates inside the range but disallowed by** `allowed-dates`
- Class: `v-date-picker-date--not-allowed`
Optionally, expose corresponding named slots or props, but at a minimum, distinct classes will let us write custom styles:

```scss
.v-date-picker-date--out-of-range {
  opacity: 0.4;
}

.v-date-picker-date--not-allowed {
  text-decoration: line-through;
  color: rgba(255, 0, 0, 0.7);
}
```
