### ISSUE TITLE
Uncompiled CSS for v-chip small attribute

### ISSUE THREAD

**Issue by nekosaur** [vuetifyjs/vuetify#231]
Can be seen here http://codepen.io/anon/pen/jBYyXK

CSS looks like this
```css
.chip--small {
    min-height: $chip-small-min-height;
    padding: $chip-small-padding;
}
```
