### ISSUE TITLE
[Feature Request] Add gutter class

### ISSUE THREAD

**Issue by devistar** [vuetifyjs/vuetify#2601]
### New Functionality
This will allow to add a gutter class between the elements of a parent instead of using padding or margin classes on each elements.

```html
<div id="app">
  <v-app id="inspire">
    <v-content>
      <v-layout row wrap class="gutter-3">
        <v-flex class="md6">
          <v-text-field label="Firstname"></v-text-field>
        </v-flex>
        <v-flex class="md6">
          <v-text-field label="Lastname"></v-text-field>
        </v-flex>
        <v-flex class="md6">
          <v-text-field label="Street"></v-text-field>
        </v-flex>
        <v-flex class="md3">
          <v-text-field label="City"></v-text-field>
        </v-flex>
        <v-flex class="md3">
          <v-text-field label="Country"></v-text-field>
        </v-flex>
        <v-flex class="md12">
          <v-text-field label="Email"></v-text-field>
        </v-flex>
      </v-layout>
    </v-content>
  </v-app>
</div>
```

```css
.gutter-3 {
  box-sizing: border-box;
  margin-left: -16px;
  margin-right: -16px;  
}

.gutter-3 > * {  
   padding-left: 16px;
   padding-right: 16px;
}
```

Codepen : https://codepen.io/anon/pen/zPWmKg

### Improvements
 There will only be one class to add on the parent element. It's faster, easier and consistent. 

### Bugs or Edge Cases it Helps Avoid
It avoids a repetitive task.
