### ISSUE TITLE
[Bug Report] Animation issues when opening second dialog from full-screen dialog

### ISSUE THREAD

**Issue by NaughtyMC** [vuetifyjs/vuetify#2984]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.2

### Steps to reproduce
1. Click *Dialog 1* button to bring up the full-screen dialog
1. Click *Dialog 2* button
1. Notice how enter transitions are not working for second dialog or the second dialog's overlay (on repeated clicks of *Dialog 2* button, transitions will work for the dialog but not the overlay)

### Expected Behavior
Both second dialog and it's overlay should both appear with the standard **v-dialog-transition**.

### Actual Behavior
On first click, both the dialog and the overlay suddenly appear after a slight delay. On repeated clicks, the dialog appears with the correct transition, but the overlay still appears suddenly and does not transition gracefully.

### Reproduction Link
[https://github.com/vuetifyjs/docs/blob/master/examples/dialogs/simple.vue](https://github.com/vuetifyjs/docs/blob/master/examples/dialogs/simple.vue)

### Other comments
I believe this has to do with the z-indices of the dialogs and the timing of when the z-index property is set.

**Comment by nekosaur** [comment]
Please provide a proper reproduction using codepen or a github repo

**Comment by NaughtyMC** [comment]
@nekosaur https://codepen.io/anon/pen/qpoKPo

**Comment by nwingt** [comment]
Temporary fix by adding the following to global CSS:
```css
.overlay--active {
  @keyframes dialog-overlay-fade-in {
    50% { opacity: 0; }
    100% { opacity: 1; }
  }
  
  animation: dialog-overlay-fade-in 0.75s ease 0s 1 both;
}
```
