### ISSUE TITLE
[Feature Request] Use rem, em instead of px

### ISSUE THREAD

**Issue by SuperDJ** [vuetifyjs/vuetify#3401]
### New Functionality
`Rem` is a scalable unit which is better for making responsive apps. Compared to `rem`, `em` can have unexpected behaviour when it comes to nesting elments

### Improvements
Have only a few units makes it easier to keep track of sizes. For even easier understanding you could use a function for calculating rem. For example a function taken from SCSS where `$font-size` is the first size set in the body in case of Vuetify `14`. The same function can also be used to calculate `em`. 

    @function rem-calc( $size, $font-size : $font-size ) {
        @return $size / ($font-size + 0px) * 1rem;
    }
    // Usage:
    font-size: rem-calc(16px)

### Bugs or Edge Cases it Helps Avoid
Prevents unexpected behavior of `em` units, improves responsiveness of an app.

**Comment by AlexandreBonneau** [comment]
This is fun, I also do something similar to that in my apps using:

```scss
/**
 * Convert the given rem size from the default browser size, to the material design one
 *
 * @param {number} $remSize
 */
@function materialFontSize($remSize) {
    $defaultFontSize  : 14; // px
    $materialFontSize : 16; // px
    $ratioDefaultMaterialFontSize : $materialFontSize / $defaultFontSize;

    @return $remSize * $ratioDefaultMaterialFontSize;
}

div {
    padding-left : materialFontSize(1rem);
}
````

This is needed when you already have a project that does not use material, then add Vuetify.
Doing so break every single element size since it hijack the root element font-size (damn you Google!).

Using this everywhere, if I were to stop using material of if Google one day decide that the root element font size should be 42, I would only need to change that function..

Anyway, `rem` is really the way to go when using CSS :100:
