### ISSUE TITLE
[Bug Report] No scrollbar of textarea

### ISSUE THREAD

**Issue by dobeerman** [vuetifyjs/vuetify#3492]
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.2
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
Just open the link

### Expected Behavior
Scrollbar on the textarea

### Actual Behavior
No scrollvbar

### Reproduction Link
[https://codepen.io/dobeerman/pen/Zrdmyj](https://codepen.io/dobeerman/pen/Zrdmyj)

### Other comments
.application--wrap in vietify.css has wrong properties

```css
.application--wrap {
  -webkit-backface-visibility: hidden;
          backface-visibility: hidden;
}
```
