### ISSUE TITLE
[Feature Request] v-card-title need align options as text

### ISSUE THREAD

**Issue by ppKrauss** [vuetifyjs/vuetify#3558]
### New Functionality
Something to control align... Perhaps reusing the strategy of `v-card-text`, so, for instance, to center a title using

    <v-card-title class="text-md-center">Test</v-card-title>

### Improvements
Same as     `<v-card-text class="title-md-center">Test</v-card-text>`

### Bugs or Edge Cases it Helps Avoid
No-align is bad to design.

**Comment by KaelWD** [comment]
`v-card-title` is a flex container for reasons unknown, so `class="justify-center"` works.

**Comment by ppKrauss** [comment]
Hi @KaelWD , thanks to the clue, is a first solution... The suggestion is also *to uniformize*.

Other problem with `justify-center`  is that is not a box-oriented. Example,  `class="cardTitle justify-center" 
```css
.cardTitle {
  border-style: dashed;
  border-width: 1px;
  width: 60%;
  border-color: #888;
}
```

is not at center.
