### ISSUE TITLE
[Feature Request] Add my-auto and ma-auto 

### ISSUE THREAD

**Issue by mdartic** [vuetifyjs/vuetify#3719]
### Problem to solve
This feature could help center elements, vertically and horizontally + vertically.

Maybe there is another way to center elements with existing features, but I didn't find them.

### Proposed solution
Write these two spacing helpers that could be implemented like this :

```css
.ma-auto {
  margin: auto;
}
.my-auto {
  margin: auto 0 auto 0;
}
```
