### ISSUE TITLE
css rule overriding expansion panel content

### ISSUE THREAD

**Issue by rzb** [vuetifyjs/vuetify#381]
### Steps to reproduce
Use `<li>` elements inside an expansion panel component, eg select components.

### What is expected ?
The inner li's should not be affected by the expansion panel's li style.

### What is actually happening ?
The inner li's are bordered due to this rule being too generic:
``` css
.expansion-panel li {
    border: 1px solid #ddd;
}
```

### Reproduction Link
[pen](http://codepen.io/rzb/pen/vmOpbe)
