### ISSUE TITLE
[Bug Report] v-btn (Raised), constant high CPU load in IE11

### ISSUE THREAD

**Issue by serdula** [vuetifyjs/vuetify#4045]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
Open page, or go to https://vuetifyjs.com/en/components/buttons#example-raised
wait a while and check CPU load and page performance with IE devtools
I also find minor visual glitch in IE11 in button toggle see the screenshot 
![v-btn](https://user-images.githubusercontent.com/2354582/39958044-61d53128-55fd-11e8-8e46-779bc4e9636f.jpg)

### Expected Behavior
CPU load goes down after few second when you do not interact with page

### Actual Behavior
CPU load remains high

### Reproduction Link
[https://codepen.io/anon/pen/mLLNJW?](https://codepen.io/anon/pen/mLLNJW?)

**Comment by KaelWD** [comment]
Can't reproduce in that codepen, only happens on the site. I also can't get IE's shit profiler to record anything so idk what's causing that.

**Comment by serdula** [comment]
Unfortunately, I’m not skill enough in html/css debugging to find real cause of this type of problem ;-(. But I found fix that somehow eliminate problems with small visual impact.

Just adding 
.btn {
      border-radius: 0;
  }

to my css helped significantly. Credit to Phlow2001 in #1301

**Comment by KaelWD** [comment]
I found this on stackoverflow, it's talking about IE9 but I wouldn't be surprised if it affects IE11 too: https://stackoverflow.com/a/13149744/2074736

**Comment by serdula** [comment]
As I have a lot of IE11 users (intranet app) I end up with IE11 specific fix
```css
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) {
  .btn {
    border-radius: 0;
  }
  .btn-toggle {
    border-radius: 0;
  }
  .btn-toggle :last-child.btn {
    border-radius: 0;
  }
  .btn-toggle :first-child.btn {
    border-radius: 0;
  }
}

```
So, chrome, edge and firefox user are not affected
It is not perfect but works, sort of

**Comment by serdula** [comment]
New IE11 fix with minimal visual impact (now really minimal)

```css
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) {
    .btn__content {
        border-radius: 0 !important;
    }
} 
```

**Comment by serdula** [comment]
As my fix stop working for vuetify v1.1 I have new version of "fix"

```css
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) {
  .v-btn::before {
    border-radius: 0 !important;
  }
}
```
For now it seems to me that cause of problems is combination of *v-btn::before border-radius: inherit* and non-zero radius, which force ie11 to some sort of endless redraw/styling loop

before:
![image](https://user-images.githubusercontent.com/2354582/42294593-73a64cb6-7fe2-11e8-8a0e-2ba9c8784c6a.png)

after:
![image](https://user-images.githubusercontent.com/2354582/42294598-7b25b45e-7fe2-11e8-8e15-49bb3ae37103.png)
