### ISSUE TITLE
[Feature Request] Prevent Vuetify from conflicting with other styles or components of user application (Vuetify css scope).

### ISSUE THREAD

**Issue by Winns** [vuetifyjs/vuetify#5041]
### Problem to solve
First of all thanks for a great framework.

I was using Vuetify for a few weeks in my test projects.
During this test a found a critical issue which could limit or completely abandon the usage of this framework for me.

Vuetify css is written in a very dangerous manner, it's using global scope without respect to any other css of your app. Most of the files in this folders contain a styles without a proper scope protection.

[generic](https://github.com/vuetifyjs/vuetify/tree/dev/src/stylus/generic)
[elements](https://github.com/vuetifyjs/vuetify/tree/dev/src/stylus/elements)
[trumps](https://github.com/vuetifyjs/vuetify/tree/dev/src/stylus/trumps)

Reserving a popular selectors like **".title"** (in my opinion selectors like this can be used only inside a scope or in very small projects) or controlling a styles of your whole app [_reset.styl](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/generic/_reset.styl).
Isn't it against a concept of reusable components that Vue.js is teaching us?

In result, it could be hard or impossible to integrate Vuetify in any project that is not limited to Vuetify.

Would it be possible to push Vuetify to another level and make it **non conflicting** with other styles or components ?
Currently to make it production ready I should manually wrap (.vuetify) all the styles of Vuetify and hope that all Vuetify components are inside this scope and work correctly.

### Proposed solution
All Vuetify components should have a global class (.vuetify or whatever),
and most of the the styles inside this files [generic](https://github.com/vuetifyjs/vuetify/tree/dev/src/stylus/generic), [elements](https://github.com/vuetifyjs/vuetify/tree/dev/src/stylus/elements), [trumps](https://github.com/vuetifyjs/vuetify/tree/dev/src/stylus/trumps) should be written relative to that class scope with respect to others styles of user application.

**Comment by I3uckwheat** [comment]
This feature would be greatly appreciated

**Comment by frank-orellana** [comment]
Thanks for the solution, I am actually doing this for my project which have existing styles, I cannot just break everythin else. So I updated the vuetify.css file to some things like this (in a many more lines of course):

````css
.vuetify *,
.vuetify ::before,
.vuetify ::after {
  box-sizing: inherit;
}
.vuetify ::before,
.vuetify ::after {
  text-decoration: inherit; /* Inherit text-decoration and vertical align to ::before and ::after pseudo elements */
  vertical-align: inherit;
}
.vuetify * {
  background-repeat: no-repeat; /* Set `background-repeat: no-repeat` to all elements */
  padding: 0; /* Reset `padding` and `margin` of all elements */
  margin: 0;
}
````

But so far I have not tried to alter the code that would add the class and instead, I add the class myself to the vuetify elements that really need this styles, for example:

````html
<v-combobox class="vuetify" v-model... />
````

As of now it is all working like a charm this way (I was about to change libraries before this), I guess I will have to update more lines in the css as my project grows but seems manageable. If someone would point me to where I would have to update the js to make it add the class automatically that would be great too, and then I would be able to submit a Pull Request if you want me to.
