### ISSUE TITLE
Glitches bottom navigation on ios

### ISSUE THREAD

**Issue by Turkyden** [vuetifyjs/vuetify#5048]
```js
<v-bottom-nav fixed color="accent" :value="true" :active.sync="e1">
  <v-btn to="/" flat color="white" value="home">
    <span>Beranda</span>
    <v-icon>home</v-icon>
  </v-btn>
  <v-btn to="/orders" flat color="white" value="orders">
    <span>Pesanan</span>
    <v-icon>history</v-icon>
  </v-btn>
  <v-btn to="/favorites" flat color="white" value="favorites">
    <span>Favorit</span>
    <v-icon>favorite</v-icon>
  </v-btn>
  <v-btn to="/profile" flat color="white" value="profile">
    <span>Profil</span>
    <v-icon>person</v-icon>
  </v-btn>
</v-bottom-nav>
```

![42145212-3582a3fc-7dea-11e8-9a5e-5b532af55e9a](https://user-images.githubusercontent.com/24560160/45140084-574b1b80-b1e4-11e8-83ed-ef8d6b7ce4bc.jpg)

You can use `<div>` instead of `<v-btn>` by change the tag of the slot of `<v-bottom-nav>`

``` js
<v-bottom-nav fixed :value="true" :active.sync="activeIndex">
  <router-link v-for="item in items" :key="item.id" :to="item.link">
    <div class="my-bottom-nav-btn" v-ripple>
      <span v-text="item.text"></span>
      <v-icon v-text="item.icon"></v-icon>
    </div>
  </router-link>
</v-bottom-nav>
```
``` css
.my-bottom-nav-btn{ 
    height: 100%; 
    color: #fff;
    opacity: 0.5; 
    display: flex; 
    align-items:center; 
    justify-content: center;
    flex-direction:column-reverse; 
    max-width: 168px;
    min-width: 80px;
    font-weight: 400;
    padding: 8px 12px 10px;
}
.router-link-active .sv-bottom-nav-btn{ opacity: 1 !important; }
```
