### ISSUE TITLE
Feature request (Menu only with icons)

### ISSUE THREAD

**Issue by cengler** [vuetifyjs/vuetify#5172]
A only menu icon component/style it would work similar to menu, but whitout backgroud and spaces

Wanted
![imagen](https://user-images.githubusercontent.com/1243214/46099261-b32e1200-c19c-11e8-8c6d-5d2b22093517.png)
Actual Menu
![imagen](https://user-images.githubusercontent.com/1243214/46099311-d2c53a80-c19c-11e8-9e76-f9a825e20d51.png)

https://codepen.io/caeycae/pen/XPvQmx

**Comment by Elfayer** [comment]
Some CSS should do the trick:
```css
.v-menu__content {
  box-shadow: none;
}

.v-list {
  background: transparent !important;
}
```
https://codepen.io/anon/pen/NOKrBN
