### ISSUE TITLE
v-radio-group and v-radio last item in row has margin top issues

### ISSUE THREAD

**Issue by ShailenNaidoo** [vuetifyjs/vuetify#5255]
### Versions and Environment
Vuetify: 1.2.7
Vue: 2.5.17
Browsers: Chrome 68
OS: Windows 10 April 2018

### Previously worked in:
Vuetify: 1.2.6
Vue: 2.5.17

### Steps to reproduce
Just upgrade to vuetify 1.2.7 and use `v-radio-group` and 2 `v-radio` components

### Expected Behavior
Expected the `v-radio-group` and `v-radio` components to behave normally like in version 1.2.6

### Actual Behavior
The last `v-radio` in `v-radio-group` has margin issues, it is displaying lower than the preceding radio buttons 

### Reproduction Link
https://codepen.io/Naidoo/pen/QZpxJV?editors=1000

---

**Comment by KaelWD** [comment]
#5162
439bf6792002188cf6ebb4db6697d362c590988d

**Comment by johnleider** [comment]
The margin is not for the details spacing, it's for spacing between the controls.

**Comment by lorenzo-w** [comment]
I think this could do it:
`.v-input--radio-group:not(.v-input--radio-group--row)
    .v-radio:not(:last-child):not(:only-child) {
    margin-bottom: 8px;
  }`

Instead of:
`.v-input--radio-group 
   .v-radio:not(:last-child):not(:only-child) {
    margin-bottom: 8px;
}`

**Comment by lorenzo-w** [comment]
I think this could do:
```css
.v-input--radio-group:not(.v-input--radio-group--row)
    .v-radio:not(:last-child):not(:only-child) {
    margin-bottom: 8px;
  }
```

Instead of:
```css
.v-input--radio-group
    .v-radio:not(:last-child):not(:only-child) {
    margin-bottom: 8px;
  }
```

Just adapt the stylus code src/stylus/components/_radio-group.styl
