### ISSUE TITLE
[Feature Request] Provides Input fields Browser Autofill Color Support

### ISSUE THREAD

**Issue by kevinmarrec** [vuetifyjs/vuetify#5269]
Trying out Vuetify Input fields, I've seen that using Google Chrome autofill (which is useful to quickly fill adresses/names/phone number/etc..) was not CSS overrided by Vuetify, which make forms visually not so nice.

### What problem does this feature solve?
Using Google Chrome Autofill it makes text fields "not so nice" with this default pale yellow, or at least there is some missing padding around the label :

![screenshot_4](https://user-images.githubusercontent.com/25272043/46807537-6cc6de80-cd6a-11e8-91cc-ff2a2a34320a.png)

### What is your proposed solution?
1) Add some CSS override around Vuetify global CSS. See https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/ to see how to change this autofill background/border color.
2) [Optional] Provides new prop OR documentation to easily change the color when the field has an "autofill" state.

**Comment by KatePavlovich** [comment]
Is there currently any solution for this problem?

**Comment by atilkan** [comment]
@KatePavlovich Use something else or make one yourself. An example for you -> https://codepen.io/atilkan/pen/GYpRwx

**Comment by onx2** [comment]
If the padding and margins were on different sections I think it might solve my problem. The color seems fine on mine (Chrome) but it doesn't fill the entire input area.

I really don't want to have to rebuild the VuetifyJS Input field and manage that as a solution since it kind of defeats the purpose of using a library.
![Capture](https://user-images.githubusercontent.com/23039725/58599708-692b8d80-824f-11e9-85ec-8602822e790f.PNG)

**Comment by johnleider** [comment]
Unfortunately this did not make the cut for v2.0 release. Thank you for your patience.

**Comment by alexquintero-deeplegal** [comment]
@kevinmarrec @atilkan @onx2 @johnleider Is there currently any solution for this problem? 🤔

**Comment by kevinmarrec** [comment]
@alexquintero-deeplegal This is something that has been pushed to the **v2.x.x** milestone for now, as it's tagged as a feature request.

So unless it becomes tagged as a bug and that someone works on it, it will kept pending for now.

**Comment by alexquintero-deeplegal** [comment]
@kevinmarrec Ok 😃, anyway a temporary solution is this:

![image](https://user-images.githubusercontent.com/54419343/64205724-aadb5e00-ce66-11e9-8b64-96d813dbfc30.png)

Create an input as it is in the image inside the form. 
It worked for me. good luck 🥳🎉

**Comment by mimbo119** [comment]
temporary solution can be implemented like this:

https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

**Comment by marcnewton** [comment]
The other answer from that link (Steve) works with a minor tweak:

```
@-webkit-keyframes autofill {
    0%,100% {
        color: inherit;
        background: transparent;
    }
}

input:-webkit-autofill {
    -webkit-animation-delay: 1s; /* Safari support - any positive time runs instantly */
    -webkit-animation-name: autofill;
    -webkit-animation-fill-mode: both;
}
```

**Comment by TobiasMSilicani** [comment]
The solution I have adopted is divided into two parts:
1 detect the autofill through css animation
`<style>
:-webkit-autofill {
    animation-name: onAutoFillStart;
}

:not(:-webkit-autofill) {
    animation-name: onAutoFillCancel;
}

@keyframes onAutoFillStart {
    from {}

    to {}
}

@keyframes onAutoFillCancel {
    from {}

    to {}
}
</style>`
2 add a placeholder = " " attribute to the autofilled input or remove it when empty
on template:
`<v-text-field @animationstart="checkAnimation"/>` 
on methods:
`checkAnimation(e) {
            if (e.animationName == "onAutoFillStart") {
                this.inputAttrs = {placeholder: ' '}
            } else if (e.animationName == "onAutoFillCancel") {
                this.inputAttrs = {}
            }
        },`

**Comment by netoramalho** [comment]
Here it is an example of how Google is applying the autofill style on their logins screen.
![Screen Shot 2020-06-04 at 11 28 40](https://user-images.githubusercontent.com/2080301/83769783-a68edc00-a656-11ea-9744-0ce0bd261b71.png)

The input fulfills the component, and the spaces are managed using padding.
![Screen Shot 2020-06-04 at 11 32 02](https://user-images.githubusercontent.com/2080301/83770115-10a78100-a657-11ea-86d7-9efbc4b329aa.png)

So far, I'm removing the style as presented by @marcnewton, but it would be nice to see Vuetify improving it.

Thank you, guys.

**Comment by valentingavran** [comment]
I have created the following CSS styles. Looks great for me. Maybe it helps somebody else

  ```css
  label.theme--dark + input:-webkit-autofill,
    input:-webkit-autofill:hover,
    input:-webkit-autofill:focus,
    input:-webkit-autofill:active {
      transition: background-color 5000s ease-in-out 0s;
      -webkit-text-fill-color: #fff !important; /* inherit only works in Safari */
      -webkit-text-size-adjust: inherit !important;
    }

    label.theme--light + input:-webkit-autofill,
    input:-webkit-autofill:hover,
    input:-webkit-autofill:focus,
    input:-webkit-autofill:active {
      transition: background-color 5000s ease-in-out 0s;
      -webkit-text-fill-color: #000 !important; /* inherit only works in Safari */
      -webkit-text-size-adjust: inherit !important;
    }

    /* When dark theme, then make keychain icon white */
    label.theme--dark + input::-webkit-credentials-auto-fill-button{
      background-color: #fff !important;
    }

    /* Hide credentials-auto-fill-button in password inputs, only visible on other inputs */
    input[type=password]::-webkit-credentials-auto-fill-button{
      visibility: hidden;
      display: none !important;
      pointer-events: none;
    }
```
