### ISSUE TITLE
Native "password reveal button" displayed beside component's icon on MS Edge

### ISSUE THREAD

**Issue by jamesxv7** [vuetifyjs/vuetify#537]
### Steps to reproduce
On a text input with the visibility icon enable, start typing on the text input.

### Versions

Microsoft Edge browser

### What is expected ?

No native "password reveal button".

### What is actually happening ?

Native "password reveal button" displayed beside component icon.

### Reproduction Link

![pass](https://cloud.githubusercontent.com/assets/121668/26030334/b64b97fe-381e-11e7-8007-4e111aaf1d5c.gif)

Note: This is an easy fix with the following css rules:
```css
input::-ms-clear,
input::-ms-reveal {
  display: none;
}
/* ::-ms-clear is for the little x on the input to clear content
not necessary for this fix */
```
