### ISSUE TITLE
Only first link is getting the selected color

### ISSUE THREAD

**Issue by asafyish** [vuetifyjs/vuetify#573]
Hi,

I have a navigation-drawer with a list inside, and on each <v-list-tile> I have 'router' and 'to', the navigation works correctly, but the selected tile icon (<v-list-tile-action>) is only selecting when the first route it active, I found that:

```css
.navigation-drawer > .list .list__tile--active:first-child .icon {
    color: #1976d2;
}
```
is causing the problem, and the fix was:
```css
.navigation-drawer > .list .list__tile--active .icon {
    color: #1976d2;
}
```
(removed :first-child.)
