### ISSUE TITLE
[Bug Report] Extra bottom border when data table has no footer

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#6429]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.4
**Browsers:** Firefox 65.0
**OS:** Ubuntu undefined

### Steps to reproduce
Define a data table component with `expand` prop set to `true` and with `hide-actions`.

### Expected Behavior
When nothing is expanded, the last row should not have bottom border set.

### Actual Behavior
Because it has it, the bottom border/shadow of the whole table gets darker.

### Reproduction Link
<a href="https://codepen.io/anon/pen/GzQGYw" target="_blank">https://codepen.io/anon/pen/GzQGYw</a>

**Comment by mitar** [comment]
I am using the following workaround:

```css
  .theme--light.v-table tbody tr:not(:last-child) {
    border-bottom: none;
  }

  .theme--light.v-table tbody tr:not(:first-child) {
    border-top: 1px solid rgba(0,0,0,0.12);
  }
```

it works great. It removes the double border on the bottom. It does not have the problem with expanded rows. And also it makes the border appear under the expanded row and now above. So it is much clearer that expanded row belongs to upper row and not the row under.
