### ISSUE TITLE
[Feature Request] Add alignment options to v-timeline

### ISSUE THREAD

**Issue by timoschwarzer** [vuetifyjs/vuetify#6594]
### Problem to solve

With the current framework options there's (as far as I know) no way to alter the 50%/50% split between the content and the `opposite` slot.

See https://github.com/vuetifyjs/vuetify/issues/6594#issuecomment-468389266

### Proposed solution

I think this needs to be discussed as I don't have a good idea for this.

**Comment by timoschwarzer** [comment]
Oh, thanks, you're right. I somehow missed these attributes.
Well, then I have to reword this issue. My intent is to resize the `opposite` slot to the minimum width. Currently it's fixed at 50% for the `opposite` slot and 50% for the actual content. I want all content on one side with the maximum width possible. :sweat_smile:

**Comment by yashdhume** [comment]
try putting the whole timeline in a  <v-container fluid></v-timeline>

**Comment by yashdhume** [comment]
try putting the whole timeline in a  container
`<v-container fluid>
   <v-timeline>
    .
    .
    .
   </v-timeline>
</v-container>
`

**Comment by ReneS1991** [comment]
Hi,

I'd like to upvote this request as I'd like to achieve the following:

![image](https://user-images.githubusercontent.com/17007821/60106433-7e6bdd00-9765-11e9-839a-529cda5c4608.png)

Currently I am overwriting the Vuetify CSS (mainly with some `!importants` 😞). Would be very nice if there is a build-in fix for this 😄 

PS: I tried the `fluid container` but that doesn't make any difference.

**Comment by gza-slc** [comment]
Upvoting too. 

Basically the same issue as @ReneS1991, I would like to reduce the width of the left column and increase the width of the right one.

![2019-09-11 21_20_05-serein io](https://user-images.githubusercontent.com/53612245/64728154-a18f6880-d4da-11e9-8ef3-a2c2851c887d.png)

**Comment by gjovanov** [comment]
You can achieve this with some custom CSS e.g. to reduce from 96px to 64px, you can use this:

```css
<style>
.v-timeline-item__divider {
  min-width: 64px;
}
.v-timeline--dense .v-timeline-item__body {
  max-width: calc(100% - 64px);
}
.v-application--is-ltr .v-timeline--dense:not(.v-timeline--reverse):before {
    left: calc(32px - 1px)
}
</style>

```
