### ISSUE TITLE
v-divider style in v-stepper-content have a margin-left: -16px

### ISSUE THREAD

**Issue by midori-tooyama** [vuetifyjs/vuetify#670]
When using v-divider in v-stepper-content, v-divider will have a margin left with -16px. I use it like this

```pug
v-stepper-content
  v-card
    v-card-row
    v-divider
    v-card-row
```

then the v-divider go out of the card from left.

# Steps to reproduce

Using v-divider in v-stepper-content

# Versions

Vuetify 0.12.5

# What is expected ?

v-divider at the right position

# What is actually happening ?

v-divider will be affect by the following style

```css
.stepper .divider {
    margin: 0 -16px;
}
```

should it be change to this?

```css
.stepper__header .divider{
    margin: 0 -16px;
}
```
