### ISSUE TITLE
[Bug Report] expansion panel style different in dev and prod

### ISSUE THREAD

**Issue by kidonng** [vuetifyjs/vuetify#7524]
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.21
**OS:** Windows 10

### Steps to reproduce
1. Clone [the repo](https://github.com/kidonng/pixiv-collection/tree/db64aa7c9be8f7445fd3e0cd9bd03e9679e5e7d0) and run (`yarn serve`).
2. Build for production (`yarn build`) and run (or [this link](https://pixiv-collection-70c86tgxh.now.sh/)).

### Expected Behavior
The style for expansion panel in production should be the same as in development:

[Chrome Devtools screenshot](https://i.loli.net/2019/06/15/5d04d701ad4db21833.png)

```css
.v-expansion-panels > *:first-child {
    border-top-left-radius: inherit;
    border-top-right-radius: inherit;
}

.v-expansion-panel {
    flex: 1 0 100%;
    max-width: 100%;
    position: relative;
    transition: 0.3s cubic-bezier(0.25, 0.8, 0.5, 1);
}

.v-expansion-panels > * {
    cursor: auto;
}

.v-item-group > * {
    flex: 1 1 auto;
}
```

### Actual Behavior
Expansion panel's `flex` declaration is overridden, thus making the second panel behaving wrongly.

[Chrome Devtools screenshot](https://i.loli.net/2019/06/15/5d04d72724c9964692.png)

```css
.v-expansion-panels>:first-child {
    border-top-left-radius: inherit;
    border-top-right-radius: inherit;
}

.v-item-group>* {
    flex: 1 1 auto;
}

.v-expansion-panel {
    flex: 1 0 100%;
    max-width: 100%;
    position: relative;
    transition: .3s cubic-bezier(.25,.8,.5,1);
}

.v-expansion-panels>* {
    cursor: auto;
}
```

### Reproduction Link
<a href="https://github.com/kidonng/pixiv-collection/tree/db64aa7c9be8f7445fd3e0cd9bd03e9679e5e7d0" target="_blank">https://github.com/kidonng/pixiv-collection/tree/db64aa7c9be8f7445fd3e0cd9bd03e9679e5e7d0</a>

### Other comments
The problem seems to be caused by Webpack (or loaders), but I can't find a better way than overriding the style myself.

**Update:** This problem seems not to always happen, waiting for more examination.
