### ISSUE TITLE
Feature Request: Tab scrollbar styling

### ISSUE THREAD

**Issue by jijoel** [vuetifyjs/vuetify#791]
I just discovered that scroll bars are working in tabs, now. Yay! Very exciting!

Currently, the scroll bars are unstyled. It would be nice (and simple, I think) for the scroll bar styling to match the site as a whole. I've attached a before (current) and after screenshot:

![image](https://user-images.githubusercontent.com/3487641/27293454-2623c402-54b2-11e7-90e8-5274fdfa6603.png)

There's a demo at https://codepen.io/jijoel/pen/yXMowz. This is the important styling:

```css
.tabs__container::-webkit-scrollbar-track
{
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
	background-color: #1976d2;
}

.tabs__container::-webkit-scrollbar
{
	height: 8px;
	background-color: #F5F5F5;
}

.tabs__container::-webkit-scrollbar-thumb
{
	background-color: #2196F3;
	border: 1px solid #555555;
}
```

This works for webkit browsers. Sadly, at this time, I'm not sure how to get it to work for IE.
