### ISSUE TITLE
[Bug Report] VBtnToggle default button height should be consistent with VBtn

### ISSUE THREAD

**Issue by AssetKid** [vuetifyjs/vuetify#7985]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Opera
**OS:** Windows, Android, Mac OSX, Linux, iOS

### Steps to reproduce
1. Create a VBtnToggle with 2/3 VBtns in it then proceed to create a standalone VBtn (or use the codepen linked below to save some time)

2. Look closely at the buttons in VBtnToggle and note down their heights.

3. Now move your attention to the standalone button and note down its height.

4. Compare the recorded height from step 2 above to the recorded height from step 3 above

### Expected Behavior
A VBtn inside a VBtnToggle should have the same default height as a standalone VBtn.

### Actual Behavior
They are not the same size. ༼ つ ◕_◕ ༽つ

Why is the standalone VBtn's default height `36px` but quickly changes to `48px` when it is in a VBtnToggle?

```css
.v-btn:not(.v-btn--round).v-size--default {
    height: 36px;
    min-width: 64px;
    padding: 0 16px;
}
```

```css
.v-btn-toggle > .v-btn.v-size--default {
    height: 48px;
    min-height: 0;
    min-width: 48px;
    padding: 0 12px;
}
```

It think we can all agree that the default height should be equal for all buttons. No?

### Reproduction Link
<a href="https://codepen.io/anon/pen/NQrGXp" target="_blank">https://codepen.io/anon/pen/NQrGXp</a>

### Other comments

> Consistency! Consistency! Consistency! 
> - Steve Ballmer
