### ISSUE TITLE
[Bug Report] v-bottom-navigation 's app attribute not work after `npm run build`

### ISSUE THREAD

**Issue by sheiun** [vuetifyjs/vuetify#8019]
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1. create an project and add <v-bottom-navigation app> ...
2. use vue-cli to build

### Expected Behavior
v-bottom-navigation--fixed > v-item-group (relative)
`position: fixed;` will be apply after build

### Actual Behavior
v-item-group > v-bottom-navigation--fixed
`position: relative;` will be apply

### Reproduction Link
<a href="https://codepen" target="_blank">https://codepen</a>

### Other comments
It works on development server (`npm run serve`), but broken on `npm run build && serve -s dist`

I thought the priority of the css in development mode and deployment

development // `<style>`

```css
.v-bottom-navigation--fixed {
  position: fixed;
}

.v-item-group {
  ~~position: relative;~~
}
```

deployment // `http://localhost:5000/css/chunk-vendors.46a4a241.css:1`

```css
.v-item-group {
  position: relave
}

.v-bottom-navigation--fixed {
    ~~position: fixed;~~
}
```

By the way, html seems the same in both.

```html
<div class="v-bottom-navigation v-item-group theme--light v-bottom-navigation--grow v-bottom-navigation--fixed">...</div>
```
