### ISSUE TITLE
[Bug Report] Don't apply hover to VTextField and VTextArea on devices that don't support hover

### ISSUE THREAD

**Issue by WIStudent** [vuetifyjs/vuetify#8546]
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
1. Open the reproduction link on a mobile device
2. Don't press into the textfield, but directly below it. The hover state will be applied to that field (outlined black instead of grey)

### Expected Behavior
Hover state should not be applied when pressing below a textfield on a mobile device.

### Actual Behavior
Hover state (outlined black instead of grey) is applied to a textfield when pressing below it on a mobile device.

### Reproduction Link
<a href="https://codepen.io/wistudent/full/zYOqdpP" target="_blank">https://codepen.io/wistudent/full/zYOqdpP</a>

### Other comments
Possible solution: Using media queries to detect if the device supports hover. Right now I am using this to temporarily fix the issue in my code:
```css
@media (hover: hover) {
  .theme--light.v-text-field--outlined:not(.v-input--is-focused):not(.v-input--has-state):hover fieldset {
    border-color: rgba(0,0,0,.86);
  }
}
@media (hover: none) {
  .theme--light.v-text-field--outlined:not(.v-input--is-focused):not(.v-input--has-state):hover fieldset {
    border-color: rgba(0,0,0,.24) !important;
  }
} 
```
