### ISSUE TITLE
[Bug Report] v-data-table pagination formatting error in IE11

### ISSUE THREAD

**Issue by taylor-misch** [vuetifyjs/vuetify#9185]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows 8.1

### Steps to reproduce
Using the code from the code snippet in CodePen, view the v-data-table in an IE11 browser. 

### Expected Behavior
The pagination on the bottom right corner should be well spaced and functionality should work as expected. 
[Working in Chrome Image Link](https://drive.google.com/file/d/19vDFQ6eQOYnayo7tL3FK3tQXQWUZoRWN/view?usp=sharing)

### Actual Behavior
In Internet Explorer 11, the pagination options are overlapping and not formatted correctly, some of the functionality appears to work, but without selectable options. (the drop down has empty fields to select).  
[Broken in IE11 Image Link](https://drive.google.com/file/d/1gDDAJCZuGGK45sZjcVw8m7TNp668wflp/view?usp=sharing) 

### Reproduction Link
<a href="https://codepen.io/taylor-misch/pen/dybxmxj?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/taylor-misch/pen/dybxmxj?&editable=true&editors=101#anon-signup</a>

### Other comments
It was hard to create a reproducible link for this error because CodePen is not supported in IE11. However, if you run a basic example like this in a local environment and view it through the IE11 browser, the error should be easily reproduced.

**Comment by johnleider** [comment]
@nekosaur — are you still looking to get this in for 2.1.x?

**Comment by johnleider** [comment]
This did not make it in time for v2.1.x.

**Comment by maiorano84** [comment]
Also noticing this same issue in IE11 on Windows 10.

Is there a projected fix for this? Or a possible path forward for a manual styling patch or unstable branch?

**Comment by maiorano84** [comment]
Menu rendering issue is related to #8338 

Absolutely positioned menus in IE 11 have an incorrect width and can't autoscale properly. "Workaround" is to set a min-width on the menu, however that doesn't solve the issue as dynamic widths still can't be calculated.

**Comment by Mikilll94** [comment]
Is there any progress on this?

**Comment by maiorano84** [comment]
@Mikilll94 There doesn't appear to be. No Vuetify collaborators appear to be interested in addressing bug reports associated with IE11.

I have a patch outlined above, but won't be able to put in a PR until I can verify that it's acceptable as an actual solution and won't have far-reaching consequences that I'm currently unaware of. In the meantime, it looks like we're on our own.

**Comment by nekosaur** [comment]
You are more than welcome to submit a PR

**Comment by maiorano84** [comment]
@nekosaur 

> I have a patch outlined above, **but won't be able to put in a PR until I can verify that it's acceptable as an actual solution** and won't have far-reaching consequences that I'm currently unaware of.

Please read the comments before going out of your way to be unhelpful. If you would like to double-check my work, you're free to contribute something meaningful to the conversation.

In the meantime, the patch above is largely untested outside of my own personal use-case and is not ready for a PR until we get more eyes on it.

**Comment by MajesticPotatoe** [comment]
I believe the point of that comment was largely to say, we are actively looking for contributors, and by submitting a PR (GitHub has this great little draft feature which would be perfect for this) would actual allow for others to see and play with it in the actual source code, which would also allow for it to be tested outside of your use-case and against the rest of the framework.

We welcome you to submit a PR so the community can easily test it and provide feedback (and eventually hopefully a fix).

**Comment by Threnos** [comment]
I will leave my solution to this. It is nowhere perfect, but does the job.

`@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
.v-data-footer__select {
      flex: none !important;
    }
    .v-data-footer__select .v-select__selection {
      min-width: 25px !important;
    }
    .v-data-footer__select .v-input {
      margin: 13px !important;
    }
    .v-data-footer__select .v-input__append-inner {
      padding-left: 10px !important;
    }
}`

**Comment by HYPE-Thomas** [comment]
We are also having this issue. Data tables in IE11 don't show elements in the pagination drop-down. It would be great if this issue could get addressed.

**Comment by deraw** [comment]
We're also having this issue, this is our workaround:
```scss
// Import visually-hidden mixin
@import 'vuetify/src/styles/tools/_display.sass';

// Fix VDataTable pagination on IE
.v-data-footer__select {
	// Vuetify applies `flex: 0 0 0` which doesn't work properly on IE 11
	// Disabling `flex` fixes it while keeping the desired behavior
	flex: none;

	// The selection is shrunk because `flex: 0 1 0` is applied on `.v-select`
	// and `flex: 1 1` on `.v-select__selections`
	// Setting the values to `0 1 auto` and `1 1 auto` fixes it, but there is a
	// glitch while the input is focused, the width isn't calculated properly
	.v-select,
	.v-select__selections {
		// Not using flex here fixes these issues
		flex: none;
		display: block;
	}

	// Since `.v-select` is now `display: block`, the input is displayed
	// and takes a lot of space, hide it with visually-hidden
	// to keep it accessible by screen readers
	input {
		@include visually-hidden;
	}
}

// Fix VDataTable pagination dropdown on IE only
// (we cannot target this case specifically)
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
	// On IE the dropdown list is shrunk, set a min-width has a workaround
	// (only on IE to avoid side effects)
	.v-list-item__content {
		min-width: 20px;
	}
}
```
I think it handles most cases!
The trickier part is the list in the menu, the only uncovered case to my knowledge is if you have a text longer that `20px`, some of it will be truncated (but displayed properly in the selection). You may need to adujst this value, whith French language we had to use `38px`
