### ISSUE TITLE
[Feature Request] Color Picker should allow hiding alpha controls through a property

### ISSUE THREAD

**Issue by jarkkolaine** [vuetifyjs/vuetify#9590]
### Problem to solve
In my use case, I need to use the color picker to set HEX colors without an alpha value. 

This works well if an existing hex string without an alpha component is passed as the value. However, in most cases, the UI starts with an empty default value — in which case the component automatically decides to show the alpha controls as well.

### Proposed solution
Add a property, e.g. "hideAlphaControls", that would force the editor in a non-alpha mode

This should then affect the computed property in VColorPicker.ts:

```
hideAlpha (): boolean {
     return this.hideAlphaControls || (this.value && !hasAlpha(this.value))
},
```

**Comment by ligne13** [comment]
Yes please !

**Comment by ligne13** [comment]
In the meantime:

```
watch: {
    color(value) {
      if (value.toString().match(/#[a-zA-Z0-9]{8}/)) {
        this.color = value.substr(0, 7);
      }
    },
}
```

color is the v-model of the <v-color-picker> component.

**Comment by ligne13** [comment]
In the meantime:
```
watch: {
    color(value) {
      // temporary fix while there is no way to disable the alpha channel in the colorpicker component: https://github.com/vuetifyjs/vuetify/issues/9590
      if (value.toString().match(/#[a-zA-Z0-9]{8}/)) {
        this.color = value.substr(0, 7);
      }
    }
}
```

`color` is the `v-model` of the `<v-color-picker-component>`.

**Comment by LuckyNoS7evin** [comment]
Side note, I found this as I wanted to do the same.

Here is a little SCSS which is very specific to hiding the alpha controls when in hexa mode. Use the code supplied by @ligne13 for the change

```html
<v-color-picker class="no-alpha" flat hide-mode-switch></v-color-picker>
```
```scss

.no-alpha {
  .v-color-picker__controls {
    .v-color-picker__preview {
      .v-color-picker__sliders {
        .v-color-picker__alpha {
          display: none;
        }
      }
    }
    .v-color-picker__edit {
      .v-color-picker__input:last-child {
        display: none;
      }
    }
  }
}
```
