### ISSUE TITLE
[Bug Report] Button size is not changed to accommodate custom loader content

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#9672]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
When using <template v-slot:loader> to define custom loader content for button, if this content is wider than original button text then content will overflow to the outside of button.

### Expected Behavior
Accommodate button size (width) so that custom loader template can fit in.

### Actual Behavior
Button size stays the same and in case loader content is larger than that it will go outside button.

### Reproduction Link
<a href="https://codepen.io/milost1982/pen/WNNgwoq?&editable=true&editors=111" target="_blank">https://codepen.io/milost1982/pen/WNNgwoq?&editable=true&editors=111</a>

### Other comments
Reproduction link is based on the example from the loaders sections in the v-btn page https://vuetifyjs.com/en/components/buttons

**Comment by MathewtheCoder** [comment]
Can i take this up ?

**Comment by jacekkarczmarczyk** [comment]
Sure @MathewtheCoder

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/pull/9823#issuecomment-560136570

**Comment by remidenele** [comment]
I have the same problem. As it is considered as working as intended, you can eventually force it via css:

```css
<style scoped>

/deep/ .my-large-loader-btn.v-btn--loading .v-btn__content {
  display: none;
}
/deep/ .my-large-loader-btn.v-btn--loading .v-btn__loader {
  position: relative;
}

<style>
```
